/**
 * Combat action continuity engine — direct TypeScript port of h3studio's
 * combat_action_engine.py (66KB, pure data transformation, zero UI).
 *
 * Provenance: /mnt/ssd/h3studio/combat_action_engine.py @ 2bc8c907, read-only
 * reference. Function names deliberately mirror the Python source so the two
 * files can be audited side by side; the golden fixtures in
 * combat-fixtures/python-golden.json are generated by running the REAL Python
 * engine (verify/combat/gen-golden.py) and every port behaviour is locked to
 * them — drift dies at test time, not render time.
 *
 * Why rows are loosely typed: the Python engine mutates schemaless plan/shot
 * dicts (user-editable Timeline fields). `PyRow` keeps that shape faithfully;
 * the typed adapter (combat-adapter.ts) is the real boundary slatecrew sees.
 * Crash-path divergence: Python float() raises on garbage where pyFloat falls
 * back — only observable on inputs Python itself would crash on.
 */

export type PyRow = Record<string, unknown>;

// ---- python semantics helpers ---------------------------------------------

/** Python `float(x or fb)` with the source's except-branch fallback folded in. */
function pyFloat(v: unknown, fb: number): number {
  const t = v === undefined || v === null || v === false || v === 0 || v === "" ? fb : v;
  const n = typeof t === "number" ? t : Number(t);
  return Number.isFinite(n) ? n : fb;
}

/** Python `bool(x)` on get-with-False semantics. */
function pyBool(v: unknown): boolean {
  return Boolean(v ?? false);
}

function isRow(v: unknown): v is PyRow {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Python str.strip / lstrip / rstrip with a character SET (not a substring). */
function stripSet(s: string, chars: string, mode: "both" | "start" | "end" = "both"): string {
  let a = 0;
  let b = s.length;
  const set = new Set([...chars]);
  if (mode === "both" || mode === "start") {
    while (a < b && set.has(s[a]!)) a++;
  }
  if (mode === "both" || mode === "end") {
    while (b > a && set.has(s[b - 1]!)) b--;
  }
  return s.slice(a, b);
}

/** Code points, not UTF-16 units — Python len()/slicing counts code points. */
function cpLen(s: string): number {
  return [...s].length;
}

function cpSlice(s: string, start: number, end?: number): string {
  return [...s].slice(start, end).join("");
}

/** Python round(): half to even, on the exact double. */
function pyRound(x: number): number {
  const fl = Math.floor(x);
  const diff = x - fl;
  if (diff > 0.5) return fl + 1;
  if (diff < 0.5) return fl;
  return fl % 2 === 0 ? fl : fl + 1;
}

/**
 * Python f"{x:.2f}" — correctly rounded decimal of the exact double, ties to
 * even. Doubles ≥ 0.05 have decimal expansions terminating well within 60
 * digits, so toFixed(60) is the exact expansion for this engine's range.
 */
function fmt2(x: number): string {
  const neg = x < 0 || Object.is(x, -0);
  const t = Math.abs(x).toFixed(60);
  const dot = t.indexOf(".");
  const ip = t.slice(0, dot);
  const fp = t.slice(dot + 1);
  let keep = fp.slice(0, 2).padEnd(2, "0");
  const rest = fp.slice(2);
  if (rest.length > 0) {
    const first = rest.charCodeAt(0) - 48;
    const restNonZero = /[1-9]/.test(rest.slice(1));
    let roundUp = first > 5 || (first === 5 && restNonZero);
    if (first === 5 && !restNonZero) {
      const lastDigit = keep.charCodeAt(1) - 48;
      roundUp = lastDigit % 2 === 1;
    }
    if (roundUp) {
      let frac = Number(keep) + 1;
      let int = Number(ip);
      if (frac === 100) {
        frac = 0;
        int += 1;
      }
      keep = String(frac).padStart(2, "0");
      const body = `${int}.${keep}`;
      return (neg && !(int === 0 && frac === 0) ? `-${body}` : body);
    }
  }
  const body = `${ip}.${keep}`;
  return neg && !(Number(ip) === 0 && Number(keep) === 0) ? `-${body}` : body;
}

function pad2(n: number): string {
  return String(Math.trunc(n)).padStart(2, "0");
}

function collapseWs(s: string): string {
  return s.split(/\s+/).filter((w) => w !== "").join(" ");
}

function dedupe<T>(list: T[]): T[] {
  return [...new Set(list)];
}

// ---- constants (verbatim from combat_action_engine.py) ---------------------

export const STREET_FIGHTER_SKILL = "street-fighter-live-action-h3";
export const HONG_KONG_COMIC_FIGHTER_SKILL = "hong-kong-comic-fighter";
export const COMBAT_ACTION_SKILLS: ReadonlySet<string> = new Set([
  STREET_FIGHTER_SKILL,
  HONG_KONG_COMIC_FIGHTER_SKILL,
]);
export const COMBAT_ACTION_SCHEMA_VERSION = 3;
export const COMBAT_FACT_LEDGER_SCHEMA_VERSION = 1;
export const COMBAT_FACT_AUTHORITY = [
  "explicit_user_direction",
  "loaded_picture_pixels",
  "explicit_role_binding",
  "blip_overview",
  "ai_enrich",
  "special_skill_default",
] as const;

export const ACTION_CAUSALITY_CONTRACT =
  "COMBAT ACTION CONTINUITY: every exchange follows load and weight, acceleration, attack line, " +
  "contact or visible miss, defender response, force and displacement, then one environment result " +
  "that triggers the next Beat. Preserve position, facing, velocity, height/support, guard or grip, " +
  "advantage and visible aftermath across Shot boundaries; no neutral reset or unexplained ownership change.";

export const FACT_LEDGER_CONTRACT =
  "COMBAT FACT LEDGER: explicit user direction outranks loaded P1/P2 pixels, explicit role " +
  "bindings, BLIP Overview, AI Enrich and Skill defaults in that order. Text metadata may " +
  "describe but never replace loaded pixels. Every explicitly bound character identity, wardrobe " +
  "and action ownership remains stable unless the user changes it; P numbering alone never " +
  "creates an S1/P1 or S2/P2 binding.";

export const FIVE_DUTY_CONTRACT =
  "FIVE-DUTY ACTION WINDOW: each 15-second combat window progresses through state pickup, " +
  "escalation, advantage shift, environment consequence and outgoing relay without adding " +
  "new Segments or resetting the fight.";

export const ACTION_CARRIER_CONTRACT =
  "ACTION CARRIER ROUTING: route each Beat through bare-hand strike, kick, grapple, throw or " +
  "ground control. Do not introduce a weapon, giant object or supernatural carrier unless " +
  "the user explicitly requested it.";

export const DYNAMIC_CAMERA_CONTRACT =
  "ACTION-TRIGGERED CAMERA: the one principal physical FPV move in each Shot is selected by " +
  "the active strike, defence, grip, throw, ground exchange or reversal and continues from " +
  "the preceding camera sector; no fixed frontal reset, in-place spin or lens zoom.";

export const CAUSAL_VALIDATION_CONTRACT =
  "CAUSAL RISK VALIDATION: silently verify every Beat's load, trajectory, response, contact, " +
  "force, displacement and next trigger; verify each following Shot inherits at least four of " +
  "position, facing, velocity, support, advantage and environment aftermath. Deterministic " +
  "generated defects are repaired automatically; ambiguous user-authored conflicts remain visible warnings.";

export const FINAL_COMBAT_RESOLUTION_CONTRACT =
  "FINAL COMBAT RESOLUTION: complete the last authored technique at real-time speed, visibly " +
  "dissipate its momentum, settle both fighters on readable support with no new attack, and let " +
  "the action-triggered FPV camera decelerate into a stable three-quarter composition for the " +
  "last 0.75-1.00 second. No zoom, in-place spin, walk-away, replay or slow-motion contact.";

const REQUIRED_BEAT_FIELDS = [
  "load_weight", "trajectory", "defensive_response", "contact_kind",
  "force_vector", "displacement", "next_trigger",
] as const;

const STATE_RELAY_KEYS = [
  "positions", "facing", "velocity", "support", "advantage", "environment_aftermath",
] as const;

const ALLOWED_ACTION_CARRIERS = new Set([
  "bare_hand_strike", "kick", "grapple_clinch", "throw_takedown", "ground_control",
]);

// ---- regexes (Python (?i) → /i flag; search-only patterns carry no /g) ------

const BEAT_TAG_RE = /\[BEAT\s+\d+[^\]]*\]/gi;
const ACTOR_RE = /\b(S[12])\b/i;
const DEFENCE_RE =
  /\b(?:parr(?:y|ies|ied)|block(?:s|ed)?|evad(?:e|es|ed)|duck(?:s|ed)?|slip(?:s|ped)?|check(?:s|ed)?|sprawl(?:s|ed)?|frame(?:s|d)?|guard(?:s|ed)?)\b|招架|格挡|格擋|闪避|閃避|下潜|下潛|防守|防御|防禦/i;
const SAFE_ACTOR_FIX_RE =
  /\b(?:parr(?:y|ies|ied)|block(?:s|ed)?|check(?:s|ed)?)\b|招架|格挡|格擋|提胫|提脛/i;
const GROUND_CAPTURE_RE =
  /single[- ]leg|double[- ]leg|captures?\s+(?:the\s+)?leg|takedown|抱腿|抱摔/i;
const TOP_CONTROL_RE =
  /side control|mount(?:ed)?|top control|ground[- ]and[- ]pound|上位压制|上位壓制|侧压|側压/i;
const REVERSAL_RE =
  /reversal|reverses?|scramble|bridge|hip escape|counter|switch(?:es)?|反转|反轉|逆转|逆轉|桥式|橋式|虾行|蝦行/i;

const WEAPON_RE =
  /\b(?:sword|knife|blade|gun|pistol|rifle|staff|bat|hammer|weapon)\b|剑|劍|刀|枪|槍|棍|棒|锤|錘|武器/i;
const SUPERNATURAL_RE =
  /\b(?:superpower|magic|spell|telekinesis|giant|kaiju|energy beam|laser beam)\b|超能力|魔法|法术|法術|巨人|怪兽|怪獸|能量光束|激光/i;
const GROUND_RE =
  /\b(?:ground[- ]and[- ]pound|side control|mount|half guard|submission|choke|armbar|bridge|hip escape|mat[- ]level|tap(?:s|ped)?)\b|地面|压制|壓制|绞|絞|关节|關節|拍地/i;
const THROW_RE =
  /\b(?:throw|takedown|hip turn|hip-turn|foot sweep|single[- ]leg|double[- ]leg|slam)\b|抱摔|摔投|投技|足扫|足掃|扫摔|掃摔/i;
const GRAPPLE_RE =
  /\b(?:grapple|clinch|underhook|overhook|whizzer|grip|arm drag|wrist capture)\b|擒拿|缠抱|纏抱|抓握|抱腿|锁臂|鎖臂|腕抓/i;
const KICK_RE =
  /\b(?:kick|knee|shin|foot|leg attack|roundhouse|side kick|oblique)\b|踢|膝|胫|脛|腿/i;
/** Defined (unused) in the Python source too — exported for import parity. */
export const STRIKE_RE =
  /\b(?:punch|palm|elbow|forearm|strike|parry|block|trap|uppercut|jab|cross)\b|拳|掌|肘|前臂|击|擊|格挡|格擋|招架|截击|截擊/i;
const ACTION_INITIATION_RE =
  /\b(?:attack|strike|punch|kick|palm|elbow|forearm|jab|cross|uppercut|parr(?:y|ies|ied)|block|check|sweep|clinch|grip|capture|throw|takedown|slam|drive|redirect|counter|evade|dodge|frame|sprawl|bridge|hip[- ]?escape|contact|impact|launch|charges?)\b|拳|踢|掌|肘|击|擊|格挡|格擋|招架|闪避|閃避|扫|掃|擒拿|抓握|摔|抱|压制|壓制|反击|反擊/i;
const OUTCOME_ONLY_RE =
  /\b(?:lands?\s+(?:on|back)|falls?|is\s+down|lies?|stands?\s+over|ends?\s+up|gets?\s+knocked|is\s+thrown|recoils?|is\s+sent|remains?\s+on\s+the\s+ground)\b|blood (?:appears|starts|becomes visible)|starts? bleeding|倒地|躺下|站在.+上方|被击飞|被擊飛|落地|趴在地上|躺在地上|退到|出现血|出現血|开始流血|開始流血/i;
const GENERIC_ACTION_RE =
  /already within arm'?s reach.*(?:attack|defence|counter).*exchange|combat footwork carries|immediate full-speed attack|brief held moment|fighters? hold a tense standoff|looks? directly(?: at)?|raises? (?:his|her|their) (?:right |left )?fist|generic (?:attack|defence|combat)|(?:continue|continues) (?:its|their) backward trajectory|摆出格斗架势|保持对峙|短暂停顿|互相看着|举起拳头/i;
const AFTERMATH_ONLY_RE =
  /final settle|final hold|aftermath|no new attack|dust settles|wind carries|debris (?:falls|settles)|camera (?:settles|holds)|余波|尘埃落下|塵埃落下|风沙消散|風沙消散|不再攻击|不再攻擊|最终定格|最終定格/i;
const MISS_RE =
  /\b(?:miss|evad|duck|slip|withdraw)\w*\b|闪避|閃避|落空|躲开|躲開/i;
const FORCE_LEFT_RE = /\b(?:left|leftward)\b|向左|左侧|左側/i;
const FORCE_RIGHT_RE = /\b(?:right|rightward)\b|向右|右侧|右側/i;
const FORCE_DOWN_RE = /\b(?:down|downward|slam|drop|floor|ground)\b|向下|落地|地面|压下|壓下/i;
const FORCE_UP_RE = /\b(?:up|upward|rising|uppercut|lift)\b|向上|上挑|抬起/i;
const FORCE_BACK_RE =
  /\b(?:backward|backwards|retreat|recoil|toward the back|back toward)\b|向后|向後|后退|後退/i;
const FORCE_HEAVY_RE = /\b(?:heavy|hard|explosive|slam|driv(?:e|es|en|ing))\b|重击|重擊|爆发|爆發|猛推/i;

const DUTIES: [string, string][] = [
  ["state_pickup", "inherit the exact incoming pose, distance, grip and momentum, then apply immediate pressure"],
  ["escalation", "raise speed or technical complexity with a different attack-response mechanism"],
  ["advantage_shift", "change angle, height, grip or top/bottom advantage through a visible cause"],
  ["environment_consequence", "make one authored contact affect the current material after impact"],
  ["outgoing_relay", "resolve the collision into a precise state that directly launches the next window"],
];

const CAMERA_SECTORS = [
  "front three-quarter eye level",
  "low left-side profile",
  "rear-left shoulder level",
  "high rear oblique",
  "right-side hip level",
  "opposite front three-quarter eye level",
  "low front shin level",
  "left-side shoulder level",
  "rear three-quarter hip level",
  "opposite high oblique",
  "right-side eye level",
  "front three-quarter hip level",
] as const;

// ---- small helpers ---------------------------------------------------------

function skillEnabled(value: unknown): boolean {
  return COMBAT_ACTION_SKILLS.has(String(value ?? "").trim().toLowerCase());
}

export function combat_baseline_duration(plan: PyRow): number {
  const actual = Math.max(0.5, pyFloat(plan.duration_seconds, 0.5));
  const authored = pyFloat(plan._speech_timing_base_duration, actual);
  return Math.min(actual, Math.max(0.5, authored));
}

function withoutBeatTags(value: unknown): string {
  return collapseWs(String(value ?? "").replace(BEAT_TAG_RE, "")).trim();
}

function splitTwoBeats(value: unknown): string[] {
  const text = withoutBeatTags(value);
  if (!text) return [];
  const parts = text
    .split(/(?<=[.!?。！？；;])\s+|\n+/)
    .map((row) => stripSet(row, " \t\r\n.;；。"))
    .filter((row) => stripSet(row, " \t\r\n.;；。") !== "");
  if (parts.length <= 2) return parts;
  return [parts[0]!, parts.slice(1).join(". ")];
}

function firstActor(value: string): string {
  const match = ACTOR_RE.exec(value);
  return match?.[1]?.toUpperCase() ?? "";
}

function opponent(actor: string): string {
  return actor === "S1" ? "S2" : "S1";
}

function replaceFirstActor(value: string, actor: string): string {
  return value.replace(ACTOR_RE, actor);
}

function timeTag(beatNumber: number, start: number, end: number): string {
  return `[BEAT ${pad2(beatNumber)} | ${fmt2(start)}-${fmt2(end)}s]`;
}

function compact(value: unknown, limit = 210): string {
  let text = stripSet(collapseWs(String(value ?? "")), " .");
  if (cpLen(text) > limit) {
    text = stripSet(cpSlice(text, 0, limit - 1), " ,;:") + "…";
  }
  return text;
}

function actionSignature(value: unknown): string {
  const text = withoutBeatTags(value).toLowerCase();
  return text.replace(/\bS[12]\b|[^a-z0-9㐀-鿿]+/g, " ").trim();
}

function actionWasUserEdited(shot: PyRow): boolean {
  return (
    pyBool(shot.combat_action_chain_user_edited) ||
    pyBool(shot.subject_action_user_edited) ||
    pyBool(shot.action_user_edited)
  );
}

function causalTargetHint(shot: PyRow, sourceWorldOnly = false): string {
  const text = [
    shot.environment_interaction,
    shot.environment_response,
    shot.location_transition,
  ]
    .map((v) => String(v ?? ""))
    .join(" ")
    .toLowerCase();
  if (sourceWorldOnly) {
    if (["rock", "stone", "cliff", "mountain", "岩", "石", "山"].some((t) => text.includes(t))) {
      return "the established source-visible rock surface";
    }
    if (["water", "river", "sea", "lake", "水", "河", "海", "湖"].some((t) => text.includes(t))) {
      return "the established source-visible water edge";
    }
    if (["wall", "column", "building", "structure", "墙", "牆", "柱", "建筑", "建築"].some((t) => text.includes(t))) {
      return "the established source-visible structural surface";
    }
    return "the established source-image combat surface";
  }
  if (["gate", "latch", "闸", "閘", "门闩", "門閂"].some((t) => text.includes(t))) {
    return "the loading gate latch";
  }
  if (["crate", "produce", "菜箱", "货箱", "貨箱"].some((t) => text.includes(t))) {
    return "the nearest wet produce crate";
  }
  if (["puddle", "wet floor", "水洼", "水窪", "积水", "積水"].some((t) => text.includes(t))) {
    return "the shallow floor puddle";
  }
  return "the established combat lane";
}

function synthesizeDistinctCausalAction(
  shot: PyRow,
  opts: { actor: string; previousAction: string; sourceWorldOnly?: boolean },
): string {
  const { actor, previousAction } = opts;
  const sourceWorldOnly = opts.sourceWorldOnly ?? false;
  const defender = opponent(actor);
  const previousCarrier = route_action_carrier(previousAction)[0];
  const target = causalTargetHint(shot, sourceWorldOnly);
  if (target === "the loading gate latch") {
    return (
      `${actor} uses a controlled hip-turn to redirect ${defender} toward the loading gate; ` +
      `${defender} braces against the latch and the shared momentum opens the route.`
    );
  }
  if (previousCarrier === "kick") {
    return (
      `${actor} captures ${defender}'s wrist and upper arm, turning the checked kick into a close clinch; ` +
      `${defender} posts a forearm and pivots to keep balance beside ${target}.`
    );
  }
  if (previousCarrier === "grapple_clinch") {
    return (
      `${actor} changes level into a controlled outside foot sweep against ${defender}; ` +
      `${defender} hops, releases the grip and regains a guarded base beside ${target}.`
    );
  }
  if (previousCarrier === "throw_takedown") {
    return (
      `${actor} posts a forearm and frames against ${defender}'s shoulder to stop the throw follow-through; ` +
      `${defender} circles out and re-establishes a standing guard beside ${target}.`
    );
  }
  if (previousCarrier === "ground_control") {
    return (
      `${actor} bridges and hip-escapes from the grounded pressure, turning the bodies toward ${target}; ` +
      `${defender} follows the rotation and keeps one readable grip without a neutral reset.`
    );
  }
  return (
    `${actor} angles off with a short open-palm entry toward ${defender}'s guard; ` +
    `${defender} parries outward and shifts one step along the established combat lane.`
  );
}

function synthesizeHighDensityCombatAction(shot: PyRow, index: number, sourceWorldOnly = false): string {
  const actor = index % 2 === 0 ? "S1" : "S2";
  const defender = opponent(actor);
  const target = causalTargetHint(shot, sourceWorldOnly);
  const exchanges = [
    `${actor} plants the rear foot and fires a straight lead palm along the centreline; ` +
      `${defender} checks the wrist with the outside forearm, slips off-line and drives a compact counter elbow that turns both bodies toward ${target}`,
    `${actor} snaps a jab-cross at head and ribs without resetting the feet; ` +
      `${defender} parries the jab, absorbs the cross on a tight elbow shield and answers with a rising knee that forces one diagonal recovery step`,
    `${actor} catches the near wrist and collar during the incoming strike, steps hip-to-hip and rotates through a controlled hip throw; ` +
      `${defender} posts the free hand, redirects the fall and lands on one knee still facing ${actor}`,
    `${actor} attacks the planted lead leg with a low outside kick; ` +
      `${defender} shin-checks the kick, drops the checking foot forward and whips a short roundhouse across the opened shoulder line`,
    `${actor} closes into an underhook-and-wrist clinch, loads weight through the hips and drives laterally; ` +
      `${defender} widens the base, frames at the jaw and pivots the pressure into a shoulder throw beside ${target}`,
    `${actor} launches a body hook from a low level change; ` +
      `${defender} seals the ribs with an elbow frame, traps the punching arm and reaps the support foot so the missed force becomes a visible stumble`,
    `${actor} shoots for a single-leg capture after the opponent's forward step; ` +
      `${defender} sprawls the hips, circles behind the shoulder and converts the stopped takedown into a standing back-control turn`,
    `${actor} bridges from the grounded pressure and hip-escapes toward ${target}; ` +
      `${defender} follows the rotation, releases the failing grip and both regain unequal standing guards without a neutral reset`,
  ];
  return `${exchanges[index % exchanges.length]}.`;
}

function synthesizeGroundReversal(currentAction: string, previousAction: string): string {
  const topActor = firstActor(currentAction) || firstActor(previousAction) || "S1";
  const bottomActor = opponent(topActor);
  return (
    `${bottomActor} visibly bridges and hip-escapes to reverse the previous ground position; ` +
    `${topActor} follows the reversal and re-establishes control without a neutral reset.`
  );
}

function synthesizeOutcomeCauseAction(shot: PyRow, index: number, sourceWorldOnly = false): string {
  const attacker = index % 2 === 0 ? "S1" : "S2";
  const defender = opponent(attacker);
  const target = causalTargetHint(shot, sourceWorldOnly);
  return (
    `${attacker} catches ${defender}'s advancing guard, changes level and completes a controlled ` +
    `outside foot sweep into ${target}; ${defender} loses the support foot, lands on the back along ` +
    `the force vector, and ${attacker} follows into a readable standing-over position without a reset.`
  );
}

function mediaEvidence(row: PyRow): [string, string] {
  const raw = String(
    row.raw_analysis_summary || row.recognition || row.analysis_summary || "",
  );
  for (const pattern of [
    /^BLIP\s*[·-]?\s*Overview\s*[:：]\s*(.+)$/im,
    /^BLIP\s+visual\s+caption\s*[·-]?\s*full\s+frame\s*[:：]\s*(.+)$/im,
    /^Overview\s*[:：]\s*(.+)$/im,
  ]) {
    const match = pattern.exec(raw);
    if (match) return ["blip_overview", compact(match[1], 320)];
  }
  const enriched = String(row.semantic_enrichment ?? "").trim();
  if (enriched) return ["ai_enrich", compact(enriched, 320)];
  return ["loaded_picture_pixels", "loaded visual reference; descriptive analysis unavailable"];
}

export function build_combat_fact_ledger(
  plan: PyRow,
  existingMedia?: PyRow[] | null,
  opts: { authored_requirement?: unknown; special_skill_key?: unknown } = {},
): PyRow {
  const authoredRequirement = opts.authored_requirement ?? "";
  const skillKey = String(opts.special_skill_key ?? STREET_FIGHTER_SKILL).trim().toLowerCase();
  const inventory: Record<string, PyRow> = {};
  for (const row of existingMedia ?? []) {
    if (!isRow(row) || !pyBool(row.loaded)) continue;
    const mediaId = String(row.media_id ?? "").trim().toUpperCase().replace(/^@+/, "");
    const mediaType = String(row.media_type || row.type || "").toLowerCase();
    if ((mediaId === "P1" || mediaId === "P2") && mediaType === "image") {
      inventory[mediaId] = row;
    }
  }

  const bound = new Set(
    ((plan.existing_media_uses as PyRow[] | undefined) ?? [])
      .filter(isRow)
      .map((row) => String(row.media_id ?? "").toUpperCase().replace(/^@+/, "")),
  );
  const subjects: PyRow[] = [];
  for (const [speaker, mediaId] of [["S1", "P1"], ["S2", "P2"]] as const) {
    if (skillKey === HONG_KONG_COMIC_FIGHTER_SKILL) {
      subjects.push({
        speaker,
        media_id: "",
        loaded: false,
        identity_authority: "explicit_user_direction_and_source_panel_evidence",
        descriptive_evidence_source: "loaded comic Pictures",
        description:
          "resolve this fighter from explicit names/roles and all source panels; " +
          "P1/P2 numbering does not imply one Picture per fighter",
        source_chain: [
          "explicit_user_direction", "loaded_picture_pixels", "shot_continuity",
        ],
        locked_attributes: [
          "face", "apparent_age", "skin_tone", "hair", "body_proportions",
          "upper_wardrobe", "lower_wardrobe", "footwear", "accessories",
          "signature_ability",
        ],
      });
      continue;
    }
    const row = inventory[mediaId];
    const [evidenceSource, description] = mediaEvidence(row ?? {});
    const loaded = row !== undefined;
    const sourceChain = ["special_skill_default"];
    if (bound.has(mediaId)) sourceChain.unshift("explicit_role_binding");
    if (loaded) {
      sourceChain.unshift("loaded_picture_pixels");
      if (evidenceSource === "blip_overview" || evidenceSource === "ai_enrich") {
        sourceChain.push(evidenceSource);
      }
    }
    subjects.push({
      speaker,
      media_id: mediaId,
      loaded,
      identity_authority: loaded ? "loaded_picture_pixels" : "special_skill_default",
      descriptive_evidence_source: evidenceSource,
      description,
      source_chain: dedupe(sourceChain),
      locked_attributes: [
        "face", "apparent_age", "skin_tone", "hair", "body_proportions",
        "upper_wardrobe", "lower_wardrobe", "footwear", "accessories",
      ],
    });
  }

  const request = compact(authoredRequirement, 500);
  return {
    schema_version: COMBAT_FACT_LEDGER_SCHEMA_VERSION,
    authority_order: [...COMBAT_FACT_AUTHORITY],
    user_direction: request,
    subjects,
    permissions: {
      weapons: WEAPON_RE.test(request),
      supernatural_carriers:
        skillKey === HONG_KONG_COMIC_FIGHTER_SKILL || SUPERNATURAL_RE.test(request),
    },
    environment: {
      source: skillKey === HONG_KONG_COMIC_FIGHTER_SKILL
        ? "loaded_picture_pixels"
        : "special_skill_default",
      value: skillKey === HONG_KONG_COMIC_FIGHTER_SKILL
        ? "derive location, terrain, weather, light and materials from the current comic Pictures"
        : "connected Kowloon-style wet seafood and vegetable market to rainy exterior alley",
    },
    conflicts: [],
  };
}

export function combat_fact_prompt_context(ledger: PyRow): string {
  const subjects: string[] = [];
  for (const row of (ledger.subjects as PyRow[] | undefined) ?? []) {
    if (!isRow(row)) continue;
    subjects.push(
      `${String(row.speaker ?? "")}=${row.loaded ? `@${String(row.media_id ?? "")}` : "Skill default"}; ` +
        `identity authority=${String(row.identity_authority ?? "")}; description only=${String(row.description ?? "")}`,
    );
  }
  const permissions = (ledger.permissions as PyRow | undefined) ?? {};
  return compact(
    "FACT AUTHORITY " + ((ledger.authority_order as string[] | undefined) ?? [...COMBAT_FACT_AUTHORITY]).join(" > ") +
      ". " + subjects.join("; ") +
      `. weapons=${permissions.weapons ? "allowed" : "not requested"}` +
      `; supernatural carriers=${permissions.supernatural_carriers ? "allowed" : "not requested"}`,
    760,
  );
}

export function combat_story_duty(startSeconds: number, endSeconds: number): [number, string, string] {
  const midpoint = (Math.max(0.0, startSeconds) + Math.max(startSeconds, endSeconds)) / 2.0;
  const relative = midpoint % 15.0;
  const index = Math.min(4, Math.floor(relative / 3.0));
  const [name, instruction] = DUTIES[index]!;
  return [index + 1, name, instruction];
}

export function route_action_carrier(
  value: unknown,
  opts: { permissions?: PyRow | null } = {},
): [string, string[]] {
  const text = String(value ?? "");
  const permissions = opts.permissions ?? {};
  const warnings: string[] = [];
  if (WEAPON_RE.test(text) && !pyBool(permissions.weapons)) {
    warnings.push("weapon carrier was not explicitly requested");
  }
  if (SUPERNATURAL_RE.test(text) && !pyBool(permissions.supernatural_carriers)) {
    warnings.push("supernatural or giant carrier was not explicitly requested");
  }
  if (GROUND_RE.test(text)) return ["ground_control", warnings];
  if (THROW_RE.test(text)) return ["throw_takedown", warnings];
  if (GRAPPLE_RE.test(text)) return ["grapple_clinch", warnings];
  if (KICK_RE.test(text)) return ["kick", warnings];
  return ["bare_hand_strike", warnings];
}

export function infer_force_vector(
  value: unknown,
  opts: { actor?: string; carrier?: string } = {},
): PyRow {
  const actor = opts.actor ?? "S1";
  const carrier = opts.carrier ?? "";
  const text = String(value ?? "").toLowerCase();
  let horizontal: string;
  if (FORCE_LEFT_RE.test(text)) horizontal = "screen-left";
  else if (FORCE_RIGHT_RE.test(text)) horizontal = "screen-right";
  else horizontal = actor === "S1" ? "screen-right" : "screen-left";
  let vertical: string;
  if (FORCE_DOWN_RE.test(text)) vertical = "downward";
  else if (FORCE_UP_RE.test(text)) vertical = "upward";
  else vertical = "level";
  const depth = FORCE_BACK_RE.test(text) ? "backward" : "forward";
  const magnitude =
    carrier === "throw_takedown" || carrier === "ground_control" || FORCE_HEAVY_RE.test(text)
      ? "heavy"
      : "medium";
  const label = `${horizontal}, ${vertical}, ${depth}`;
  return { horizontal, vertical, depth, magnitude, label };
}

function structuredBeat(
  text: string,
  beatId: number,
  opts: { fallbackActor: string; permissions: PyRow },
): [PyRow, string[]] {
  const actor = firstActor(text) || opts.fallbackActor;
  const defender = opponent(actor);
  const [carrier, warnings] = route_action_carrier(text, { permissions: opts.permissions });
  const force = infer_force_vector(text, { actor, carrier });
  const miss = MISS_RE.test(text);
  const label = String(force.label);
  return [
    {
      beat_id: beatId,
      attacker: actor,
      defender,
      carrier,
      mechanic: compact(text, 220),
      load_weight: force.magnitude === "heavy" ? "committed body weight" : "balanced body weight",
      trajectory: label,
      contact_kind: miss ? "visible_miss" : "visible_contact_or_guard_contact",
      defensive_response: miss ? "evade and angle change" : "absorb, parry, frame or redirect visibly",
      force_vector: force,
      displacement: `${defender} displaces ${label} while ${actor} recovers without resetting`,
      next_trigger: "recoil, grip or displacement becomes the next Beat's load",
    },
    warnings,
  ];
}

function dynamicCameraRoute(
  carrier: string,
  action: string,
  startSector: string,
  endSector: string,
  beatId: number,
): [string, string, string] {
  const lowered = action.toLowerCase();
  const orbitDirection = Math.floor((beatId - 1) / 2) % 2 === 0 ? "clockwise" : "counterclockwise";
  let relation: string;
  let motion: string;
  if (REVERSAL_RE.test(lowered)) {
    relation = "counter";
    motion = `a tight ${orbitDirection} reframe arc around the visible advantage reversal`;
  } else if (carrier === "kick") {
    relation = "follow";
    motion = `a low-to-hip ${orbitDirection} lateral FPV arc following the planted foot and kick line`;
  } else if (carrier === "grapple_clinch") {
    relation = "follow";
    motion = `a tight shoulder-height ${orbitDirection} FPV arc tracking the grip and torso drive`;
  } else if (carrier === "throw_takedown") {
    relation = "counter";
    motion = `a descending hip-to-floor ${orbitDirection} FPV arc countering the throw momentum`;
  } else if (carrier === "ground_control") {
    relation = "follow";
    motion = `a mat-level ${orbitDirection} lateral FPV orbit keeping grip and top/bottom ownership readable`;
  } else if (DEFENCE_RE.test(lowered)) {
    relation = "counter";
    motion = `a short ${orbitDirection} counter-move into the parry line with one restrained contact shake`;
  } else {
    relation = "follow";
    motion = `a shoulder-height ${orbitDirection} lateral FPV pass following the strike line`;
  }
  const trigger = `BEAT ${pad2(beatId)} load starts the move; contact or visible miss completes it`;
  const direction =
    `physical FPV ${orbitDirection} orbital translation: ${motion}, physically translating from ${startSector} to ${endSector}; ${trigger}. ` +
    "Maintain close subject scale, visible parallax and a readable horizon; no lens retreat or in-place rotation.";
  return [relation, trigger, direction];
}

function stateText(vector: PyRow): string {
  return Object.entries(vector).map(([key, value]) => `${key}=${value}`).join("; ");
}

function synthesizeAllowedCarrierAction(
  shot: PyRow,
  actor: string,
  previousAction: string,
  sourceWorldOnly = false,
): string {
  return synthesizeDistinctCausalAction(shot, {
    actor,
    previousAction: previousAction || "standing bare-hand exchange",
    sourceWorldOnly,
  });
}

function stableFinalResolution(resultActor: string, carrier: string): string {
  const defender = opponent(resultActor);
  if (carrier === "ground_control" || carrier === "throw_takedown") {
    return (
      `${resultActor} completes the current control and settles on a planted kneeling base; ` +
      `${defender} completes the displacement into a stable guarded recovery on the same support ` +
      "surface. Both stop changing position; no new strike, submission or reset begins"
    );
  }
  return (
    `${resultActor} completes the current recoil into a planted guard while ${defender} finishes ` +
    "the caused displacement and braces in a stable guarded stance. Both stop changing position; " +
    "no new attack, exit movement or pose reset begins"
  );
}

function causalValidationIssues(
  structuredBeats: PyRow[],
  incomingVector: PyRow,
  previousOutgoingVector: PyRow | null,
  cameraTrigger: string,
): [string[], string[]] {
  const issues: string[] = [];
  for (const beat of structuredBeats) {
    const missing = REQUIRED_BEAT_FIELDS.filter((field) => !beat[field]);
    if (missing.length > 0) {
      issues.push(`BEAT ${pad2(pyFloat(beat.beat_id, 0))} lacks ${missing.join(", ")}`);
    }
    if (!ALLOWED_ACTION_CARRIERS.has(String(beat.carrier ?? ""))) {
      issues.push(`unsupported action carrier ${String(beat.carrier ?? "")}`);
    }
  }
  let inherited: string[] = [];
  if (previousOutgoingVector) {
    inherited = STATE_RELAY_KEYS.filter(
      (key) =>
        key in incomingVector &&
        key in previousOutgoingVector &&
        incomingVector[key] === previousOutgoingVector[key],
    );
    if (inherited.length < 4) {
      issues.push("next Shot inherits fewer than four state fields from the preceding outgoing state");
    }
  }
  if (!String(cameraTrigger ?? "").toUpperCase().includes("BEAT")) {
    issues.push("camera move is not bound to a concrete Beat");
  }
  return [issues, inherited];
}

export function reconcile_final_combat_markers(
  markers: unknown,
  durationSeconds: unknown,
): PyRow[] {
  const duration = Math.max(0.5, pyFloat(durationSeconds, 0.5));
  const result = (Array.isArray(markers) ? markers : []).filter(isRow).map((m) => structuredClone(m));
  const finalRows: PyRow[] = [];
  for (const marker of result) {
    const markerText = `${String(marker.preset ?? "")} ${String(marker.direction ?? "")}`.toLowerCase();
    if (["final", "ending", "terminal", "最后", "最終"].some((token) => markerText.includes(token))) {
      finalRows.push(marker);
    }
  }
  if (finalRows.length === 0) {
    finalRows.push({ time_seconds: pyRound(Math.max(0.0, duration - 1.0) * 2.0) / 2.0 });
    result.push(finalRows[0]!);
  }
  for (const marker of finalRows) {
    marker.time_seconds = pyRound(Math.max(0.0, duration - 1.0) * 2.0) / 2.0;
    marker.preset = "Final Combat Resolve";
    marker.direction =
      "Complete the final authored technique at real-time speed, show recoil and caused " +
      "displacement, then settle both fighters on readable support while the physical FPV " +
      "camera decelerates into a stable eye-level three-quarter composition through the last frame.";
  }
  return result;
}

function sortShots(rows: unknown[]): PyRow[] {
  return [...rows]
    .filter(isRow)
    .map((row) => structuredClone(row))
    .sort((a, b) => {
      const as = pyFloat(a.start_seconds, 0.0);
      const bs = pyFloat(b.start_seconds, 0.0);
      if (as !== bs) return as - bs;
      const ae = pyFloat(a.end_seconds, 0.0);
      const be = pyFloat(b.end_seconds, 0.0);
      if (ae !== be) return ae - be;
      const aid = String(a.id || a.cue_id || "");
      const bid = String(b.id || b.cue_id || "");
      return aid < bid ? -1 : aid > bid ? 1 : 0;
    });
}

export function reconcile_combat_action_rows(
  rows: unknown,
  durationSeconds: unknown,
  opts: {
    action_baseline_seconds?: unknown;
    fact_ledger?: PyRow | null;
    auto_repair?: boolean;
    source_world_only?: boolean;
  } = {},
): [PyRow[], string[]] {
  const autoRepair = opts.auto_repair ?? true;
  const sourceWorldOnly = opts.source_world_only ?? false;
  const duration = Math.max(0.5, pyFloat(durationSeconds, 0.5));
  const baseline = Math.min(
    duration,
    Math.max(
      0.5,
      pyFloat(opts.action_baseline_seconds === undefined ? duration : opts.action_baseline_seconds, 0.5),
    ),
  );
  const shots = sortShots(Array.isArray(rows) ? rows : []);
  const warnings: string[] = [];
  const factLedger: PyRow = opts.fact_ledger ?? {
    authority_order: [...COMBAT_FACT_AUTHORITY],
    subjects: [],
    permissions: { weapons: false, supernatural_carriers: false },
  };
  let factContext = combat_fact_prompt_context(factLedger);
  if (!(((factLedger.subjects as unknown[]) ?? []).length > 0)) {
    const inheritedContext = shots
      .map((row) => String(row.combat_fact_context ?? "").trim())
      .find((text) => text !== "") ?? "";
    if (inheritedContext) factContext = inheritedContext;
  }
  const permissions = (factLedger.permissions as PyRow | undefined) ?? {};
  let previousOutgoing = "";
  let previousOutgoingVector: PyRow | null = null;
  let previousSignature = "";
  let previousAction = "";
  let previousCameraSector: string = CAMERA_SECTORS[0];
  let beatNumber = 1;

  shots.forEach((shot, index) => {
    const shotId = String(shot.id || shot.cue_id || `Shot ${index + 1}`);
    const start = Math.max(0.0, pyFloat(shot.start_seconds, 0.0));
    const end = Math.min(duration, Math.max(start + 0.05, pyFloat(shot.end_seconds, start + 0.5)));
    const actionEnd = start < baseline ? Math.min(end, baseline) : end;
    const midpoint = start + (actionEnd - start) / 2.0;
    let rawAction = withoutBeatTags(shot.subject_action);
    if (
      rawAction &&
      GENERIC_ACTION_RE.test(rawAction) &&
      !AFTERMATH_ONLY_RE.test(rawAction) &&
      autoRepair &&
      !actionWasUserEdited(shot)
    ) {
      shot.causal_risk_original_action = rawAction;
      rawAction = synthesizeHighDensityCombatAction(shot, index, sourceWorldOnly);
      shot.causal_risk_repair_status = "auto_fixed";
      shot.causal_risk_repair_notes =
        "Replaced a vague pose/standoff/generic exchange with one concrete load, " +
        "attack line, defence, contact response and displacement chain.";
    }
    let beats = splitTwoBeats(rawAction);
    let status: "continuous" | "auto_fixed" | "warning" = "continuous";
    const notes: string[] = [];

    if (shot.causal_risk_repair_status === "auto_fixed") {
      status = "auto_fixed";
      notes.push("replaced generic choreography with a distinct causal exchange");
    }

    if (beats.length === 0) {
      beats = [
        "S1 initiates one committed close-range attack toward S2",
        "S2 visibly defends and immediately redirects the resulting momentum",
      ];
      status = "auto_fixed";
      notes.push("missing choreography replaced by one attack-response exchange");
    } else if (beats.length === 1) {
      const attacker0 = firstActor(beats[0]!) || (index % 2 === 0 ? "S1" : "S2");
      const defender0 = opponent(attacker0);
      beats.push(`${defender0} visibly absorbs, evades or redirects that exact attack and remains engaged`);
      status = "auto_fixed";
      notes.push("missing defender response was added");
    }

    const joinedBeats = beats.join(" ");
    if (OUTCOME_ONLY_RE.test(joinedBeats) && !ACTION_INITIATION_RE.test(joinedBeats)) {
      if (autoRepair && !actionWasUserEdited(shot)) {
        const originalAction = joinedBeats;
        const repairedAction = synthesizeOutcomeCauseAction(shot, index, sourceWorldOnly);
        shot.causal_risk_original_action = originalAction;
        shot.causal_risk_repair_status = "auto_fixed";
        shot.causal_risk_repair_notes =
          "Inserted the missing initiation, contact, force direction and displacement " +
          "before the authored outcome-only landing/standing result.";
        beats = splitTwoBeats(repairedAction);
        status = "auto_fixed";
        notes.push("inserted a physical cause before an outcome-only action");
      } else {
        status = "warning";
        notes.push("outcome-only action has no explicit initiating contact");
      }
    }

    let attacker = firstActor(beats[0]!) || (index % 2 === 0 ? "S1" : "S2");
    let responseActor = firstActor(beats[1] ?? "");
    if (responseActor === attacker && DEFENCE_RE.test(beats[1] ?? "")) {
      const opp = opponent(attacker);
      if (!new RegExp(`\\b${opp}\\b`, "i").test(beats[1] ?? "")) {
        if (SAFE_ACTOR_FIX_RE.test(beats[1] ?? "")) {
          beats[1] = replaceFirstActor(beats[1]!, opp);
          status = "auto_fixed";
          notes.push("clear self-defence actor was corrected to the opponent");
        } else {
          status = "warning";
          notes.push("possible self-response needs an explicit opponent attack or actor correction");
        }
      }
    }

    let currentAction = beats.join(" ");
    if (
      previousAction &&
      GROUND_CAPTURE_RE.test(previousAction) &&
      TOP_CONTROL_RE.test(currentAction) &&
      !REVERSAL_RE.test(currentAction)
    ) {
      if (autoRepair && !actionWasUserEdited(shot)) {
        const originalAction = currentAction;
        const repairedAction = synthesizeGroundReversal(currentAction, previousAction);
        shot.causal_risk_original_action = originalAction;
        shot.causal_risk_repair_status = "auto_fixed";
        shot.causal_risk_repair_notes =
          "Inserted an explicit bridge/hip-escape reversal before the ownership change.";
        beats = splitTwoBeats(repairedAction);
        currentAction = beats.join(" ");
        attacker = firstActor(beats[0]!) || attacker;
        status = "auto_fixed";
        notes.push("inserted an explicit ground reversal to preserve top/bottom ownership");
      } else {
        status = "warning";
        notes.push("ground-control ownership changes without an explicit reversal");
      }
    }

    let signature = actionSignature(currentAction);
    if (signature && signature === previousSignature) {
      if (autoRepair && !actionWasUserEdited(shot)) {
        const originalAction = currentAction;
        const repairedAction = synthesizeDistinctCausalAction(shot, {
          actor: attacker,
          previousAction,
          sourceWorldOnly,
        });
        const repairedSignature = actionSignature(repairedAction);
        if (repairedSignature && repairedSignature !== previousSignature) {
          shot.causal_risk_original_action = originalAction;
          shot.causal_risk_repair_status = "auto_fixed";
          shot.causal_risk_repair_notes =
            "Replaced a repeated action with a distinct causal continuation while preserving actors and direction.";
          beats = splitTwoBeats(repairedAction);
          currentAction = beats.join(" ");
          signature = repairedSignature;
          attacker = firstActor(beats[0]!) || attacker;
          status = "auto_fixed";
          notes.push("replaced repeated action with a distinct causal continuation");
        } else {
          status = "warning";
          notes.push("action exchange repeats the preceding Shot");
        }
      } else {
        status = "warning";
        notes.push("action exchange repeats the preceding Shot");
      }
    }

    responseActor = firstActor(beats[1] ?? "");

    const [dutyIndex, dutyName, dutyInstruction] = combat_story_duty(start, actionEnd);
    let structuredBeats: PyRow[] = [];
    const carrierWarnings: string[] = [];
    for (const [beatOffset, beatText] of beats.slice(0, 2).entries()) {
      const fallbackActor = beatOffset === 0 ? attacker : opponent(attacker);
      const [structured, routedWarnings] = structuredBeat(beatText, beatNumber + beatOffset, {
        fallbackActor,
        permissions,
      });
      structuredBeats.push(structured);
      carrierWarnings.push(...routedWarnings);
    }
    if (carrierWarnings.length > 0) {
      if (autoRepair && !actionWasUserEdited(shot)) {
        const originalAction = currentAction;
        const repairedAction = synthesizeAllowedCarrierAction(
          shot,
          attacker,
          previousAction,
          sourceWorldOnly,
        );
        beats = splitTwoBeats(repairedAction);
        currentAction = beats.join(" ");
        signature = actionSignature(currentAction);
        attacker = firstActor(beats[0]!) || attacker;
        structuredBeats = [];
        const remainingWarnings: string[] = [];
        for (const [beatOffset, beatText] of beats.slice(0, 2).entries()) {
          const fallbackActor = beatOffset === 0 ? attacker : opponent(attacker);
          const [structured, routedWarnings] = structuredBeat(beatText, beatNumber + beatOffset, {
            fallbackActor,
            permissions,
          });
          structuredBeats.push(structured);
          remainingWarnings.push(...routedWarnings);
        }
        shot.causal_risk_original_action = originalAction;
        shot.causal_risk_repair_status = "auto_fixed";
        shot.causal_risk_repair_notes =
          "Replaced an unrequested weapon, giant-object or supernatural carrier with " +
          "an allowed bare-hand, kick, grapple, throw or ground continuation.";
        if (remainingWarnings.length > 0) {
          status = "warning";
          notes.push(...dedupe(remainingWarnings));
        } else {
          status = "auto_fixed";
          notes.push("routed an unrequested carrier back to allowed physical combat");
        }
      } else {
        status = "warning";
        notes.push(...dedupe(carrierWarnings));
      }
    }

    const primaryBeat = structuredBeats[0]!;
    const resultBeat = structuredBeats[structuredBeats.length - 1]!;
    const carrier = String(primaryBeat.carrier);
    const forceVector: PyRow = { ...(resultBeat.force_vector as PyRow) };
    const nextSector: string = CAMERA_SECTORS[(index + 1) % CAMERA_SECTORS.length];
    const [motionRelation, initialTrigger, initialDirection] = dynamicCameraRoute(
      carrier,
      currentAction,
      previousCameraSector,
      nextSector,
      beatNumber,
    );
    let cameraTrigger = initialTrigger;
    let cameraDirection = initialDirection;

    const isFinalShot = index === shots.length - 1;
    let settleStart: number;
    let actionMidpoint: number;
    if (isFinalShot) {
      const settleDuration = Math.min(1.0, Math.max(0.25, (actionEnd - start) * 0.25));
      settleStart = Math.max(start + 0.1, actionEnd - settleDuration);
      actionMidpoint = start + Math.max(0.05, settleStart - start) / 2.0;
    } else {
      settleStart = actionEnd;
      actionMidpoint = midpoint;
    }
    let labelled =
      `${timeTag(beatNumber, start, actionMidpoint)} ${stripSet(beats[0]!, " .")}. ` +
      `${timeTag(beatNumber + 1, actionMidpoint, settleStart)} ${stripSet(beats[1]!, " .")}.`;
    const incomingVector: PyRow = previousOutgoingVector
      ? structuredClone(previousOutgoingVector)
      : {
        positions: "S1 screen-left and S2 screen-right at arm's reach",
        facing: "S1 and S2 face each other on the established combat axis",
        velocity: "both already moving inside the exchange",
        support: "both have one readable planted support foot",
        guard_or_grip: "separate live guards; no unexplained grip",
        advantage: "contested",
        environment_aftermath: sourceWorldOnly
          ? "established source-image terrain and visible materials unchanged"
          : "established wet floor and fixtures unchanged",
        wetness_damage: sourceWorldOnly
          ? "preserve only source-visible weathering, damage and non-graphic contact marks"
          : "preserve existing sweat, wetness and visible non-graphic contact marks",
      };
    const resultActor = String(resultBeat.attacker || opponent(attacker));
    const outgoingVector: PyRow = {
      positions: String(resultBeat.displacement ?? ""),
      facing: `${attacker} and ${opponent(attacker)} remain mutually oriented after the angle change`,
      velocity: String(forceVector.label ?? ""),
      support:
        carrier === "throw_takedown" || carrier === "ground_control"
          ? "one fighter low/grounded and the other base remains readable"
          : "support foot and recovery step remain visible",
      guard_or_grip:
        carrier === "grapple_clinch" || carrier === "throw_takedown" || carrier === "ground_control"
          ? `${attacker} retains the authored grip until visibly released`
          : "guard recovers from the visible contact line",
      advantage: `temporary initiative=${resultActor}; no unexplained ownership swap`,
      environment_aftermath: "pending the exact contact consequence assigned to this Shot",
      wetness_damage: sourceWorldOnly
        ? "carry only source-visible weathering, damage and contact marks into the next Beat"
        : "carry visible sweat, wetness and contact marks into the next Beat",
    };
    const incoming = previousOutgoing || stateText(incomingVector);
    let outgoing = stateText(outgoingVector);
    let nextTrigger =
      `The displacement, recoil, grip or failed defence from BEAT ${pad2(beatNumber + 1)} ` +
      `directly triggers BEAT ${pad2(beatNumber + 2)}; camera movement follows that action cause.`;

    let eventChain =
      `EVENT CAUSE: ${attacker} initiates ${carrier}; ` +
      `EVENT RESPONSE: ${String(resultBeat.defender ?? "")} visibly responds; ` +
      `EVENT CONSEQUENCE: ${String(resultBeat.displacement ?? "")}; ` +
      `NEXT EVENT: BEAT ${pad2(beatNumber + 2)} starts from this state.`;
    const physicalFeedback =
      `PHYSICAL FEEDBACK: force travels ${String(forceVector.label ?? "")} with ` +
      `${String(forceVector.magnitude ?? "")} magnitude; only a visible contact can affect the environment.`;

    let finalActionResolution = "";
    let finalCameraResolution = "";
    if (isFinalShot) {
      finalActionResolution = stableFinalResolution(resultActor, carrier);
      finalCameraResolution =
        "After the final contact and recoil are complete, decelerate the physical FPV orbit " +
        "and settle into one stable eye-level three-quarter composition with a level horizon " +
        "for the last 0.75-1.00 second; no zoom, in-place spin, replay or slow motion.";
      labelled += ` [FINAL SETTLE | ${fmt2(settleStart)}-${fmt2(actionEnd)}s] ${finalActionResolution}.`;
      outgoingVector.velocity = "settled; no further displacement after final recovery";
      outgoingVector.support = "both final support states are planted and readable";
      outgoingVector.advantage = `resolved final initiative=${resultActor}; no new exchange begins`;
      outgoing = stateText(outgoingVector);
      nextTrigger =
        "FINAL RESOLUTION: no next Beat; preserve the completed contact, settled support, " +
        "fighter orientation and environment aftermath through the last frame.";
      cameraTrigger =
        `BEAT ${pad2(beatNumber)} initiates the camera move; BEAT ${pad2(beatNumber + 1)} contact ` +
        "completes it; FINAL SETTLE begins only " +
        "after recoil and displacement finish";
      cameraDirection = `${stripSet(cameraDirection, " .")}. ${finalCameraResolution}`;
      eventChain =
        `EVENT CAUSE: ${attacker} initiates ${carrier}; ` +
        `EVENT RESPONSE: ${String(resultBeat.defender ?? "")} visibly responds; ` +
        `EVENT CONSEQUENCE: ${String(resultBeat.displacement ?? "")}; ` +
        "FINAL EVENT: momentum visibly dissipates into one stable supported end state.";
    }

    const [validationIssues, inheritedFields] = causalValidationIssues(
      structuredBeats,
      incomingVector,
      previousOutgoingVector,
      cameraTrigger,
    );
    if (status === "warning") {
      for (const note of notes) {
        if (!validationIssues.includes(note)) validationIssues.push(note);
      }
    }
    const causalValidationStatus =
      validationIssues.length > 0
        ? "warning"
        : status === "auto_fixed" || shot.causal_risk_repair_status === "auto_fixed"
          ? "auto_fixed"
          : "continuous";

    if (!pyBool(shot.combat_action_chain_user_edited)) {
      shot.combat_action_chain = labelled;
      shot.subject_action = labelled;
      shot.h3_executable_action = labelled;
    }
    if (!pyBool(shot.incoming_combat_state_user_edited)) {
      shot.incoming_combat_state = incoming;
    }
    if (!pyBool(shot.outgoing_combat_state_user_edited)) {
      shot.outgoing_combat_state = outgoing;
    }
    if (!pyBool(shot.next_action_trigger_user_edited)) {
      shot.next_action_trigger = nextTrigger;
    }
    shot.event_causality_chain = eventChain;
    shot.physical_feedback_chain = physicalFeedback;
    shot.combat_fact_context = factContext;
    shot.combat_story_duty_index = dutyIndex;
    shot.combat_story_duty = dutyName;
    shot.combat_story_duty_instruction = dutyInstruction;
    shot.combat_action_beats = structuredBeats;
    shot.combat_action_carrier = carrier;
    shot.combat_force_vector = forceVector;
    shot.incoming_combat_state_vector = incomingVector;
    shot.outgoing_combat_state_vector = outgoingVector;
    shot.camera_position_sector = `${previousCameraSector} -> ${nextSector}`;
    shot.camera_motion_relation = motionRelation;
    shot.camera_action_trigger = cameraTrigger;
    shot.dynamic_camera_direction = cameraDirection;
    shot.camera_movement = cameraDirection;
    shot.movement_speed = "Very fast";
    shot.movement_amplitude = "Large";
    shot.combat_continuity_status = status;
    shot.combat_continuity_notes = notes.join("; ");
    shot.causal_validation_status = causalValidationStatus;
    shot.causal_validation_issues = validationIssues;
    shot.causal_validation_inherited_fields = inheritedFields;
    shot.final_action_resolution = finalActionResolution;
    shot.final_camera_resolution = finalCameraResolution;
    shot.final_action_stable = isFinalShot && validationIssues.length === 0;
    shot.combat_action_schema_version = COMBAT_ACTION_SCHEMA_VERSION;

    if (notes.length > 0) {
      warnings.push(`${shotId} combat continuity ${status}: ${notes.join("; ")}.`);
    }
    previousOutgoing = String(shot.outgoing_combat_state ?? outgoing).trim();
    previousOutgoingVector = structuredClone(outgoingVector);
    previousSignature = signature;
    previousAction = currentAction;
    previousCameraSector = nextSector;
    beatNumber += 2;
  });

  return [shots, warnings];
}

export function apply_combat_action_continuity(
  plan: PyRow,
  opts: {
    special_skill_key: unknown;
    existing_media?: PyRow[] | null;
    authored_requirement?: unknown;
  },
): PyRow {
  if (!skillEnabled(opts.special_skill_key)) {
    return plan;
  }
  const baseline = combat_baseline_duration(plan);
  const existingLedger = plan.combat_fact_ledger;
  let factLedger: PyRow;
  if (isRow(existingLedger) && pyBool(existingLedger.user_edited)) {
    factLedger = structuredClone(existingLedger);
  } else {
    factLedger = build_combat_fact_ledger(plan, opts.existing_media, {
      authored_requirement: opts.authored_requirement ?? "",
      special_skill_key: opts.special_skill_key,
    });
  }
  const sourceShots = ((plan.shots as unknown[] | undefined) ?? [])
    .filter(isRow)
    .map((row) => structuredClone(row));
  const activeShots = sourceShots.filter(
    (row) => pyFloat(row.start_seconds, 0.0) < baseline - 1e-6,
  );
  const speechTailShots = sourceShots.filter(
    (row) => pyFloat(row.start_seconds, 0.0) >= baseline - 1e-6,
  );
  const [shots, warnings] = reconcile_combat_action_rows(
    activeShots,
    plan.duration_seconds === undefined ? baseline : plan.duration_seconds,
    {
      action_baseline_seconds: baseline,
      fact_ledger: factLedger,
      source_world_only:
        String(opts.special_skill_key ?? "").trim().toLowerCase() === HONG_KONG_COMIC_FIGHTER_SKILL,
    },
  );
  if (speechTailShots.length > 0) {
    const lastState = String(
      shots.length > 0 ? String(shots[shots.length - 1]!.outgoing_combat_state ?? "") : "",
    ).trim();
    const lastVector = structuredClone(
      shots.length > 0
        ? ((shots[shots.length - 1]!.outgoing_combat_state_vector as PyRow | undefined) ?? {})
        : {},
    );
    for (const tail of speechTailShots) {
      const inherited = lastState ||
        "Both fighters preserve the completed final contact, readable support, " +
        "screen orientation and persistent environmental aftermath.";
      const settle =
        "No new attack begins. Both fighters hold the completed causal end state while " +
        "dust, debris, wind and light reactions decay naturally behind the remaining speech.";
      if (!actionWasUserEdited(tail)) {
        tail.subject_action = settle;
        tail.h3_executable_action = settle;
        tail.combat_action_chain = settle;
      }
      tail.incoming_combat_state = inherited;
      tail.outgoing_combat_state = inherited;
      tail.incoming_combat_state_vector = structuredClone(lastVector);
      tail.outgoing_combat_state_vector = structuredClone(lastVector);
      tail.next_action_trigger = "FINAL RESOLUTION: no next Beat and no replay.";
      tail.camera_movement =
        "Stable eye-level three-quarter hold with a level horizon; no zoom, pull-back, " +
        "orbit, in-place spin or slow motion.";
      tail.movement_speed = "Settled";
      tail.movement_amplitude = "None";
      tail.combat_continuity_status = "speech_tail_hold";
      tail.causal_validation_status = "continuous";
      tail.causal_validation_issues = [];
      tail.final_action_resolution = settle;
      tail.final_camera_resolution = tail.camera_movement;
      tail.final_action_stable = true;
      tail.combat_action_schema_version = COMBAT_ACTION_SCHEMA_VERSION;
    }
    shots.push(...speechTailShots);
    shots.sort((a, b) => pyFloat(a.start_seconds, 0.0) - pyFloat(b.start_seconds, 0.0));
    warnings.push(
      "Dialogue-only duration extension preserves the completed combat end state; " +
      "no synthetic attack Beat is added after the authored action baseline.",
    );
  }
  plan.shots = shots;
  plan.markers = reconcile_final_combat_markers(
    plan.markers ?? [],
    plan.duration_seconds === undefined ? baseline : plan.duration_seconds,
  );
  plan.combat_fact_ledger = factLedger;
  plan.combat_fact_ledger_schema_version = COMBAT_FACT_LEDGER_SCHEMA_VERSION;
  plan.combat_action_schema_version = COMBAT_ACTION_SCHEMA_VERSION;
  plan.combat_baseline_duration_seconds = baseline;
  let constraints = String(plan.constraints ?? "").trim();
  for (const contract of [
    FACT_LEDGER_CONTRACT,
    FIVE_DUTY_CONTRACT,
    ACTION_CARRIER_CONTRACT,
    DYNAMIC_CAMERA_CONTRACT,
    ACTION_CAUSALITY_CONTRACT,
    CAUSAL_VALIDATION_CONTRACT,
    FINAL_COMBAT_RESOLUTION_CONTRACT,
  ]) {
    if (!constraints.toLowerCase().includes(contract.split(":", 1)[0]!.toLowerCase())) {
      constraints = stripSet(constraints, " .") + (constraints ? ". " : "") + contract;
    }
  }
  plan.constraints = constraints;

  const counts = new Map<number, number>();
  for (const row of shots) {
    const start = Math.max(0.0, pyFloat(row.start_seconds, 0.0));
    if (start >= baseline - 1e-6) continue;
    const segment = Math.max(0, Math.floor(start / 15.0));
    counts.set(segment, (counts.get(segment) ?? 0) + 2);
  }
  for (const segment of [...counts.keys()].sort((a, b) => a - b)) {
    const segmentStart = segment * 15.0;
    if (segmentStart >= baseline) continue;
    const count = counts.get(segment)!;
    const expected = 12;
    if (count !== expected) {
      warnings.push(
        `Combat density risk at ${fmt2(segmentStart)}-${fmt2(Math.min(baseline, segmentStart + 15.0))}s: ` +
          `${count} executable beats are present; the stable target is ${expected}.`,
      );
    }
  }

  const notices = ((plan.design_warnings as unknown[] | undefined) ?? []).map((v) => String(v));
  notices.push(...warnings);
  const active =
    "Combat Action Continuity v3 is active: authority-ranked facts, five duties, routed action " +
    "carriers, action-triggered camera motion, force vectors, silent causal validation and a stable final resolution are compiled into H3 prompts.";
  if (!notices.includes(active)) {
    notices.push(active);
  }
  plan.design_warnings = dedupe(notices);
  return plan;
}

export function combat_action_prompt_clause(row: unknown): string {
  if (!isRow(row) || !pyFloat(row.combat_action_schema_version, 0)) {
    return "";
  }
  const forceVector = (row.combat_force_vector || {}) as PyRow;
  const parts = [
    "FACT LEDGER - " + compact(row.combat_fact_context, 760),
    "STORY DUTY - " + compact(`${String(row.combat_story_duty ?? "")}: ${String(row.combat_story_duty_instruction ?? "")}`, 300),
    "ACTION CARRIER - " + compact(row.combat_action_carrier, 80),
    "ACTION STATUS - " + compact(`${String(row.combat_continuity_status ?? "")}: ${String(row.combat_continuity_notes ?? "")}`, 260),
    "FORCE VECTOR - " + compact(forceVector.label, 120),
    "ACTION-TRIGGERED CAMERA - " + compact(row.dynamic_camera_direction, 480),
    "INCOMING COMBAT STATE - " + compact(row.incoming_combat_state, 300),
    "OUTGOING COMBAT STATE - " + compact(row.outgoing_combat_state, 300),
    "NEXT ACTION TRIGGER - " + compact(row.next_action_trigger, 260),
    "EVENT CAUSALITY - " + compact(row.event_causality_chain, 360),
    "PHYSICAL FEEDBACK - " + compact(row.physical_feedback_chain, 260),
    "CAUSAL QC - " + compact(
      `${String(row.causal_validation_status ?? "")}: ` +
        ((row.causal_validation_issues as unknown[] | undefined) ?? []).map((v) => String(v)).join("; "),
      300,
    ),
    "FINAL ACTION RESOLUTION - " + compact(row.final_action_resolution, 360),
    "FINAL CAMERA RESOLUTION - " + compact(row.final_camera_resolution, 360),
  ];
  return parts.filter((part) => !part.endsWith(" - ")).join(" ");
}

const ENGINE_LINE_PREFIXES = ["[ENV-PHYSICS]", "[ENV-IN]", "[ENV-OUT]", "[LOCATION]"];
const CAST_LOCK_SENTENCE_RE = /CAST REFERENCE LOCK:[^.]*\./gis;

export function compact_street_fighter_prompt_field(
  value: unknown,
  opts: { global_contracts?: Iterable<string> } = {},
): string {
  const rows = String(value ?? "")
    .split("\n")
    .filter((row) => !ENGINE_LINE_PREFIXES.some((p) => row.trim().startsWith(p)));
  let text = rows.join("\n").trim();
  text = text.replace(
    /\[(?:ENV-PHYSICS|ENV-IN|ENV-OUT|LOCATION)\]\s*.*?(?=\[(?:ENV-PHYSICS|ENV-IN|ENV-OUT|LOCATION)\]|$)/gis,
    " ",
  );
  for (const contract of opts.global_contracts ?? []) {
    text = text.split(String(contract ?? "")).join("");
  }
  text = text.replace(CAST_LOCK_SENTENCE_RE, "");
  text = collapseWs(text);
  text = stripSet(text, " .\n");
  if (cpLen(text) > 1200) {
    text = stripSet(cpSlice(text, 0, 850), " ,;:") + " … " + cpSlice(text, -320).replace(/^\s+/, "");
  }
  return text;
}

/** ACTION_RISK flags for one reconciled shot: every causal issue the silent
 *  validator surfaced (notes are already folded in when status is warning) —
 *  the card-level risk surface the adapter forwards to events and receipts. */
export function action_risk(row: unknown): { status: string; flags: string[] } {
  if (!isRow(row)) return { status: "", flags: [] };
  const issues = ((row.causal_validation_issues as unknown[] | undefined) ?? [])
    .map((v) => String(v))
    .filter((v) => v !== "");
  const status = String(row.causal_validation_status ?? "");
  const flags = [...issues];
  if (status === "warning" && flags.length === 0) {
    flags.push(`combat continuity ${String(row.combat_continuity_status ?? "warning")} without enumerated issues`);
  }
  return { status, flags };
}
