/**
 * Segment engine — direct TypeScript port of h3studio's segment_engine.py
 * (44KB, pure planning/cache logic, zero Qt/ComfyUI dependencies).
 *
 * Provenance: /mnt/ssd/h3studio/segment_engine.py @ 2bc8c907, read-only
 * reference. Function names deliberately mirror the Python source so the two
 * files can be audited side by side; the golden fixtures in
 * segment-fixtures/python-golden.json are generated by running the REAL
 * Python engine (verify/segment/gen-golden.py) and every port behaviour is
 * locked to them — drift dies at test time, not render time.
 *
 * The editor always exposes one continuous timeline; this engine turns a work
 * area into internal, overlapping generation jobs only when it is longer than
 * the native H3 limit, keeps authored speech whole, and aligns render cuts to
 * dialogue turns.
 *
 * Divergence note (same policy as combat-action.ts): Python float()/int()
 * raise on garbage where this port yields NaN via Number() — only observable
 * on inputs Python itself would crash on. `derive_*_seed` needs BigInt:
 * results exceed Number.MAX_SAFE_INTEGER by design (2^63 domain).
 */

import { createHash } from "node:crypto";

export type PyRow = Record<string, unknown>;

// ---- python semantics helpers ---------------------------------------------

function pyFloat(v: unknown, fb: number): number {
  const t = v === undefined || v === null || v === false || v === 0 || v === "" ? fb : v;
  const n = typeof t === "number" ? t : Number(t);
  return Number.isFinite(n) ? n : fb;
}

/** Python truthiness (NaN is truthy in Python, unlike JS). */
function pyTruth(v: unknown): boolean {
  if (v === undefined || v === null || v === false) return false;
  if (typeof v === "number") return v !== 0;
  if (typeof v === "string") return v.length > 0;
  if (Array.isArray(v)) return v.length > 0;
  if (typeof v === "object") return Object.keys(v).length > 0;
  return true;
}

/** Python `x or fallback`. */
function pyOr<T>(v: T, fb: T): T {
  return pyTruth(v) ? v : fb;
}

function isRow(v: unknown): v is PyRow {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Code points, not UTF-16 units — Python len()/indexing counts code points. */
function cpLen(s: string): number {
  return [...s].length;
}

function cpSlice(s: string, start: number, end?: number): string {
  return [...s].slice(start, end).join("");
}

/**
 * CPython round(): round-half-to-even on the decimal value. JS Math.round is
 * half-toward-+∞ — wrong for 0.5/2.5/61.5-style ties (timeline grid hits them
 * constantly: 0.25s snaps to 0.0, not 0.5).
 */
function pyRound(x: number, ndigits = 0): number {
  if (!Number.isFinite(x)) return x;
  const pow = ndigits === 0 ? 1 : Math.pow(10, ndigits);
  const scaled = x * pow;
  const floor = Math.floor(scaled);
  const diff = scaled - floor;
  let result: number;
  if (Math.abs(diff - 0.5) < 1e-9) {
    // exact decimal half → to even
    result = floor % 2 === 0 ? floor : floor + 1;
  } else {
    result = Math.round(scaled);
  }
  return ndigits === 0 ? result : result / pow;
}

function pyRoundInt(x: number): number {
  return Math.trunc(pyRound(x));
}

/** Zero-pad decimal like f"{n:09d}". */
function padDigits(n: number, width: number): string {
  return String(Math.abs(n)).padStart(width, "0");
}

/** Python f"{x:.2f}" for the value classes this engine sees (2dp-exact). */
function fixed2(x: number): string {
  return x.toFixed(2);
}

function sha256Hex(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

/** Python json.dumps(sort_keys, ensure_ascii=False, separators=(",",":")). */
function pyStableDumps(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    // JSON cannot carry py int-vs-float distinction; golden inputs use ints
    // and non-integral floats only (see gen-golden fingerprint case).
    if (Object.is(value, -0)) return "-0.0";
    return String(value);
  }
  if (typeof value === "bigint") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(pyStableDumps).join(",")}]`;
  if (isRow(value)) {
    const keys = Object.keys(value).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
    return `{${keys.map((k) => `${JSON.stringify(k)}:${pyStableDumps(value[k])}`).join(",")}}`;
  }
  return JSON.stringify(String(value));
}

// ---- constants -------------------------------------------------------------

export const MAX_NATIVE_SECONDS = 15.0;
export const DEFAULT_OVERLAP_SECONDS = 1.0;
export const DEFAULT_MIN_SHOT_SECONDS = 3.0;
export const TIMELINE_GRID_SECONDS = 0.5;
export const MAX_SEED = 2n ** 63n - 1n;
export const CONTINUITY_MODES = new Set([
  "none", "hard_cut", "match_action", "motion_reference", "transition",
]);
export const SPEECH_CONTENT_ROLES = new Set(["dialogue", "voice_over", "lyrics"]);
export const SPEECH_OVERLAP_POLICIES = new Set(["auto", "overlap", "sequential"]);

// ---- timed-prose regexes ---------------------------------------------------

const TIME_TOKEN = String.raw`\d{1,2}:\d{2}(?::\d{2})?(?:\.\d{1,3})?|\d+(?:\.\d+)?`;
const TIME_TOKEN_ATOMIC = `(?:${TIME_TOKEN})`;
const UNIT_ALTS = String.raw`hours?|hrs?|h|minutes?|mins?|m|seconds?|secs?|s|秒`;

/** Python \b emulation for mixed ASCII/CJK text: py \w is unicode-wide. */
const NOT_PY_WORD = String.raw`(?![\p{L}\p{N}_])`;
const NOT_BEFORE_PY_WORD = String.raw`(?<![\p{L}\p{N}_])`;

const TIMED_TEXT_RANGE_RE = new RegExp(
  String.raw`(?<open>[\[(]?)\s*` +
  String.raw`(?:(?:from|between)\s+)?` +
  String.raw`(?<start>${TIME_TOKEN_ATOMIC})\s*` +
  String.raw`(?<start_unit>${UNIT_ALTS})?\s*` +
  String.raw`(?:-|–|—|to|through|until|and|至|到)\s*` +
  String.raw`(?<end>${TIME_TOKEN_ATOMIC})\s*` +
  String.raw`(?<end_unit>${UNIT_ALTS})?\s*` +
  String.raw`(?<close>[\]\)]?)`,
  "giu",
);
TIMED_TEXT_RANGE_RE.lastIndex = 0;

const TIMED_TEXT_POINT_RE = new RegExp(
  String.raw`(?:(?:\bat\s+|@\s*)` +
  String.raw`(?<time>${TIME_TOKEN_ATOMIC})\s*` +
  String.raw`(?<unit>${UNIT_ALTS})` +
  String.raw`|` +
  String.raw`(?<time_cn>${TIME_TOKEN_ATOMIC})\s*` +
  String.raw`(?<unit_cn>秒)(?:时|時|处|處)?)`,
  "giu",
);
TIMED_TEXT_POINT_RE.lastIndex = 0;

const LEADING_PHASE_CONNECTOR_RE = new RegExp(
  String.raw`^\s*(?:(?:and\s+)?(?:then|afterwards|subsequently)|` +
  String.raw`(?:and\s+)?transition(?:s|ed|ing)?\s+to|` +
  String.raw`(?:and\s+)?shift(?:s|ed|ing)?\s+to|followed\s+by|` +
  String.raw`while|whereas|然后|然後|随后|隨後|之后|之後|转为|轉為)` +
  NOT_PY_WORD +
  String.raw`\s*[:,：]?\s*`,
  "giu",
);

const SENTENCE_SPLIT_RE = new RegExp("[\\r\\n]+|(?<=[.!?;。！？；])");

const GEOMETRY_TAIL_RE = new RegExp(
  String.raw`^(?:°|degrees?(?![A-Za-z])|px(?![A-Za-z])|pixels?(?![A-Za-z])|` +
  String.raw`%|fps(?![A-Za-z])|frames?(?![A-Za-z])|帧|幀|度|倍|圈|个|個)`,
  "i",
);

const BRACKET_TAIL_RE = /^[\])]\s*/;

const ATOMIC_SHOT_RE = new RegExp(
  NOT_BEFORE_PY_WORD +
  String.raw`(?:signature|ultimate|finisher|finishing\s+move|named\s+technique)` +
  NOT_PY_WORD +
  String.raw`|绝招|絕招|终结技|終結技|必杀|必殺|招牌招式|` +
  String.raw`无界[\s—\-·…]*紫电拳|無界[\s—\-·…]*紫電拳|` +
  String.raw`极霸[\s—\-·…]*之拳|極霸[\s—\-·…]*之拳`,
  "iu",
);

// ---- timed prompt text ------------------------------------------------------

function timeTokenSeconds(token: string, unit = ""): number {
  const value = token.trim();
  if (value.includes(":")) {
    const parts = value.split(":").map((p) => Number(p));
    if (parts.length === 2) return parts[0]! * 60.0 + parts[1]!;
    if (parts.length === 3) return parts[0]! * 3600.0 + parts[1]! * 60.0 + parts[2]!;
    throw new Error(`Unsupported time token: ${token}`);
  }
  let seconds = Number(value);
  const normalizedUnit = unit.trim().toLowerCase();
  if (["h", "hr", "hrs", "hour", "hours"].includes(normalizedUnit)) seconds *= 3600.0;
  else if (["m", "min", "mins", "minute", "minutes"].includes(normalizedUnit)) seconds *= 60.0;
  return seconds;
}

function isPromptTimeRange(
  match: RegExpMatchArray & { indices?: unknown },
  source = "",
): boolean {
  const raw = match[0];
  const tailSource = pyOr(source, "");
  let tail = tailSource.slice(
    (match.index ?? 0) + raw.length,
    (match.index ?? 0) + raw.length + 24,
  );
  // The closing bracket is optional in the regex, so account for a match that
  // stops immediately before it during backtracking. Camera degrees, pixel
  // sizes and other numeric specifications are visual instructions, not a
  // segment-local schedule.
  tail = tail.trimStart().replace(BRACKET_TAIL_RE, "").trimStart();
  if (GEOMETRY_TAIL_RE.test(tail)) return false;
  const g = match.groups ?? {};
  return Boolean(
    g["start_unit"] ||
      g["end_unit"] ||
      (g["start"] ?? "").includes(":") ||
      (g["end"] ?? "").includes(":") ||
      g["open"] ||
      g["close"] ||
      raw.includes("秒"),
  );
}

function segmentLocalTimecode(seconds: number): string {
  const value = Math.max(0.0, Number(seconds));
  const hours = Math.trunc(value / 3600);
  const minutes = Math.trunc((value % 3600) / 60);
  const remainder = value % 60;
  const rem = remainder.toFixed(3).padStart(6, "0");
  if (hours) {
    return `${padDigits(hours, 2)}:${padDigits(minutes, 2)}:${rem}`;
  }
  return `${padDigits(minutes, 2)}:${rem}`;
}

/** Find all matches with code-point offsets (Python finditer semantics). */
function findMatches(re: RegExp, sentence: string): RegExpMatchArray[] {
  const rx = new RegExp(re.source, re.flags);
  const out: RegExpMatchArray[] = [];
  for (const m of sentence.matchAll(rx)) out.push(m);
  return out;
}

function matchCpStart(sentence: string, m: RegExpMatchArray): number {
  return cpLen(sentence.slice(0, m.index ?? 0));
}

export function scope_timed_prompt_text(
  text: string,
  window_start: number,
  window_end: number,
  opts: { field_name?: string } = {},
): string {
  const { field_name = "direction" } = opts;
  const source = pyOr(text, "").trim();
  if (!source || window_end <= window_start) return source;

  const sentences = source
    .split(SENTENCE_SPLIT_RE)
    .map((row) => row.trim())
    .filter((row) => row);
  const output: string[] = [];
  let found_schedule = false;
  let retained_schedule = false;
  for (const sentence of sentences) {
    const matches = findMatches(TIMED_TEXT_RANGE_RE, sentence).filter((m) =>
      isPromptTimeRange(m, sentence),
    );
    const point_matches = matches.length ? [] : findMatches(TIMED_TEXT_POINT_RE, sentence);
    if (!matches.length && !point_matches.length) {
      output.push(sentence);
      continue;
    }

    found_schedule = true;
    let cursor = 0; // code-point cursor
    const retained_chunks: string[] = [];
    let last_match_retained = false;
    for (const match of matches) {
      const cpStart = matchCpStart(sentence, match);
      const cpEnd = cpStart + cpLen(match[0]);
      let chunk = cpSlice(sentence, cursor, cpEnd);
      cursor = cpEnd;
      const g = match.groups ?? {};
      const start_unit = pyOr(pyOr(g["start_unit"], g["end_unit"]), "");
      const end_unit = pyOr(pyOr(g["end_unit"], g["start_unit"]), "");
      let range_start = timeTokenSeconds(g["start"] ?? "", start_unit);
      let range_end = timeTokenSeconds(g["end"] ?? "", end_unit);
      if (range_end < range_start) [range_start, range_end] = [range_end, range_start];
      if (!ranges_intersect(range_start, range_end, Number(window_start), Number(window_end))) {
        last_match_retained = false;
        continue;
      }
      const local_start = Math.max(range_start, window_start) - window_start;
      const local_end = Math.min(range_end, window_end) - window_start;
      const local_range =
        "[segment-local " +
        segmentLocalTimecode(local_start) +
        "–" +
        segmentLocalTimecode(local_end) +
        "]";
      const relative_start = cpStart - (cpEnd - cpLen(chunk));
      const relative_end = relative_start + cpLen(match[0]);
      chunk =
        cpSlice(chunk, 0, relative_start) +
        local_range +
        cpSlice(chunk, relative_end);
      chunk = chunk.replace(LEADING_PHASE_CONNECTOR_RE, "").trim();
      if (chunk) {
        retained_chunks.push(chunk);
        retained_schedule = true;
        last_match_retained = true;
      }
    }
    for (const match of point_matches) {
      const cpStart = matchCpStart(sentence, match);
      const cpEnd = cpStart + cpLen(match[0]);
      let chunk = cpSlice(sentence, cursor, cpEnd);
      cursor = cpEnd;
      const g = match.groups ?? {};
      const token = pyOr(pyOr(g["time"], g["time_cn"]), "0") as string;
      const unit = pyOr(pyOr(g["unit"], g["unit_cn"]), "") as string;
      const point = timeTokenSeconds(token, unit);
      if (point < window_start - 1e-6 || point > window_end + 1e-6) {
        last_match_retained = false;
        continue;
      }
      const local_point = Math.min(window_end - window_start, Math.max(0.0, point - window_start));
      const local_tag = "at [segment-local " + segmentLocalTimecode(local_point) + "]";
      const relative_start = cpStart - (cpEnd - cpLen(chunk));
      const relative_end = relative_start + cpLen(match[0]);
      chunk =
        cpSlice(chunk, 0, relative_start) +
        local_tag +
        cpSlice(chunk, relative_end);
      chunk = chunk.replace(LEADING_PHASE_CONNECTOR_RE, "").trim();
      if (chunk) {
        retained_chunks.push(chunk);
        retained_schedule = true;
        last_match_retained = true;
      }
    }
    if (retained_chunks.length && last_match_retained) {
      retained_chunks[retained_chunks.length - 1] =
        (retained_chunks[retained_chunks.length - 1] + cpSlice(sentence, cursor)).trim();
    }
    if (retained_chunks.length) output.push(...retained_chunks);
  }

  const scoped = output.filter((row) => row).join(" ").trim();
  if (!found_schedule) return scoped;
  const duration = window_end - window_start;
  const authority =
    `SEGMENT-LOCAL ${field_name.toUpperCase()} SCHEDULE (authoritative, ` +
    `00:00.000–${segmentLocalTimecode(duration)}): `;
  if (retained_schedule) {
    return (
      authority +
      scoped +
      " The retained timed phase overrides every untimed modifier in this field; apply " +
      "an untimed modifier only when it is compatible with that active phase." +
      " Off-window earlier and later phases were removed; do not depict, replay, " +
      "foreshadow or blend any omitted phase into this segment."
    ).trim();
  }
  if (scoped) {
    return (
      authority +
      scoped +
      " No time-scoped phase from this field is active in this segment; do not infer " +
      "one from an earlier or later phase."
    ).trim();
  }
  return "";
}

// ---- planning ---------------------------------------------------------------

export function snap_seconds(value: number, grid = TIMELINE_GRID_SECONDS): number {
  if (grid <= 0) return pyRound(Number(value), 6);
  return pyRound(pyRound(Number(value) / grid) * grid, 6);
}

export type SegmentStatus = "pending" | "cached" | string;

/** One hidden generation unit within a continuous user-visible work area. */
export class RenderSegment {
  segment_id: string;
  index: number;
  start_seconds: number;
  end_seconds: number;
  overlap_before_seconds: number;
  overlap_after_seconds: number;
  seed: number | null;
  fingerprint: string;
  status: SegmentStatus;
  output_path: string;
  error: string;
  core_start_seconds: number | null;
  core_end_seconds: number | null;
  shot_ids: string[] | null;
  continuity_mode: string;

  constructor(
    segment_id: string,
    index: number,
    start_seconds: number,
    end_seconds: number,
    fields: Partial<Omit<RenderSegment, "duration_seconds" | "toDict" | "fromDict">> = {},
  ) {
    this.segment_id = segment_id;
    this.index = index;
    this.start_seconds = start_seconds;
    this.end_seconds = end_seconds;
    this.overlap_before_seconds = fields.overlap_before_seconds ?? 0.0;
    this.overlap_after_seconds = fields.overlap_after_seconds ?? 0.0;
    this.seed = fields.seed ?? null;
    this.fingerprint = fields.fingerprint ?? "";
    this.status = fields.status ?? "pending";
    this.output_path = fields.output_path ?? "";
    this.error = fields.error ?? "";
    this.core_start_seconds = fields.core_start_seconds ?? null;
    this.core_end_seconds = fields.core_end_seconds ?? null;
    this.shot_ids = fields.shot_ids ?? null;
    this.continuity_mode = fields.continuity_mode ?? "none";
  }

  get duration_seconds(): number {
    return pyRound(this.end_seconds - this.start_seconds, 6);
  }

  toDict(): PyRow {
    return {
      segment_id: this.segment_id,
      index: this.index,
      start_seconds: this.start_seconds,
      end_seconds: this.end_seconds,
      overlap_before_seconds: this.overlap_before_seconds,
      overlap_after_seconds: this.overlap_after_seconds,
      seed: this.seed,
      fingerprint: this.fingerprint,
      status: this.status,
      output_path: this.output_path,
      error: this.error,
      core_start_seconds: this.core_start_seconds,
      core_end_seconds: this.core_end_seconds,
      shot_ids: this.shot_ids === null ? null : [...this.shot_ids],
      continuity_mode: this.continuity_mode,
    };
  }

  clone(): RenderSegment {
    return RenderSegment.fromDict(this.toDict());
  }

  static fromDict(value: PyRow): RenderSegment {
    return new RenderSegment(
      String(value["segment_id"] ?? ""),
      Number(value["index"] ?? 0),
      Number(value["start_seconds"] ?? 0),
      Number(value["end_seconds"] ?? 0),
      {
        overlap_before_seconds: value["overlap_before_seconds"] as number | undefined,
        overlap_after_seconds: value["overlap_after_seconds"] as number | undefined,
        seed: (value["seed"] ?? null) as number | null,
        fingerprint: (value["fingerprint"] ?? "") as string,
        status: (value["status"] ?? "pending") as SegmentStatus,
        output_path: (value["output_path"] ?? "") as string,
        error: (value["error"] ?? "") as string,
        core_start_seconds: (value["core_start_seconds"] ?? null) as number | null,
        core_end_seconds: (value["core_end_seconds"] ?? null) as number | null,
        shot_ids: (value["shot_ids"] ?? null) as string[] | null,
        continuity_mode: (value["continuity_mode"] ?? "none") as string,
      },
    );
  }
}

function segmentId(index: number, start: number, end: number): string {
  return (
    `segment_${padDigits(index + 1, 3)}_` +
    `${padDigits(pyRoundInt(start * 1000), 9)}_${padDigits(pyRoundInt(end * 1000), 9)}`
  );
}

function shotSegmentId(coreStart: number, coreEnd: number): string {
  return `shot_${padDigits(pyRoundInt(coreStart * 1000), 9)}_${padDigits(pyRoundInt(coreEnd * 1000), 9)}`;
}

export function plan_render_segments(
  start_seconds: number,
  end_seconds: number,
  opts: {
    max_segment_seconds?: number;
    overlap_seconds?: number;
    grid_seconds?: number;
  } = {},
): RenderSegment[] {
  const {
    max_segment_seconds = MAX_NATIVE_SECONDS,
    overlap_seconds = DEFAULT_OVERLAP_SECONDS,
    grid_seconds = TIMELINE_GRID_SECONDS,
  } = opts;
  // A work area at or below the native limit is returned unchanged as one
  // segment. This is the compatibility guarantee for existing short projects.
  const start = snap_seconds(start_seconds, grid_seconds);
  const end = snap_seconds(end_seconds, grid_seconds);
  const maximum = snap_seconds(max_segment_seconds, grid_seconds);
  const overlap = snap_seconds(overlap_seconds, grid_seconds);
  if (end <= start) throw new Error("Work-area end must be later than its start.");
  if (maximum <= 0) throw new Error("Maximum segment duration must be positive.");
  if (overlap < 0 || overlap >= maximum) {
    throw new Error("Segment overlap must be at least zero and shorter than a segment.");
  }

  if (end - start <= maximum + 1e-6) {
    return [new RenderSegment(segmentId(0, start, end), 0, start, end)];
  }

  const rows: RenderSegment[] = [];
  let cursor = start;
  while (cursor < end - 1e-6) {
    const segmentEnd = Math.min(end, snap_seconds(cursor + maximum, grid_seconds));
    const index = rows.length;
    rows.push(
      new RenderSegment(segmentId(index, cursor, segmentEnd), index, cursor, segmentEnd, {
        overlap_before_seconds: index ? overlap : 0.0,
        continuity_mode: index ? "match_action" : "none",
      }),
    );
    if (segmentEnd >= end - 1e-6) break;
    const nextCursor = snap_seconds(segmentEnd - overlap, grid_seconds);
    if (nextCursor <= cursor) {
      throw new Error("Segment settings do not advance the render cursor.");
    }
    cursor = nextCursor;
  }

  for (let index = 0; index < rows.length - 1; index++) {
    rows[index]!.overlap_after_seconds = pyRound(
      Math.max(0.0, rows[index]!.end_seconds - rows[index + 1]!.start_seconds),
      6,
    );
  }
  return rows;
}

export function plan_shot_render_segments(
  start_seconds: number,
  end_seconds: number,
  shots: PyRow[],
  opts: {
    min_segment_seconds?: number;
    max_segment_seconds?: number;
    overlap_seconds?: number;
    grid_seconds?: number;
  } = {},
): RenderSegment[] {
  const {
    min_segment_seconds = DEFAULT_MIN_SHOT_SECONDS,
    max_segment_seconds = MAX_NATIVE_SECONDS,
    overlap_seconds = DEFAULT_OVERLAP_SECONDS,
    grid_seconds = TIMELINE_GRID_SECONDS,
  } = opts;
  // Plan stable render units around authored Shot boundaries: very short
  // beats merge forward, gaps are covered, long ranges split.
  const start = snap_seconds(start_seconds, grid_seconds);
  const end = snap_seconds(end_seconds, grid_seconds);
  const minimum = Math.max(grid_seconds, snap_seconds(min_segment_seconds, grid_seconds));
  const maximum = snap_seconds(max_segment_seconds, grid_seconds);
  const overlap = Math.max(0.0, snap_seconds(overlap_seconds, grid_seconds));
  if (end <= start) throw new Error("Work-area end must be later than its start.");
  if (maximum <= 0.0 || minimum > maximum) {
    throw new Error("Shot render minimum must be positive and no longer than its maximum.");
  }

  const clipped_shots: PyRow[] = [];
  const boundaries = new Set<number>([start, end]);
  for (const source of shots) {
    const shotStart = Math.max(start, snap_seconds(pyFloat(source["start_seconds"], start), grid_seconds));
    const shotEnd = Math.min(end, snap_seconds(pyFloat(source["end_seconds"], shotStart), grid_seconds));
    if (shotEnd <= shotStart) continue;
    clipped_shots.push({
      cue_id: String(source["cue_id"] ?? source["shot_id"] ?? ""),
      start_seconds: shotStart,
      end_seconds: shotEnd,
      continuity_mode: String(source["continuity_mode"] ?? "auto"),
    });
    boundaries.add(shotStart);
    boundaries.add(shotEnd);
  }

  // No internal Shot boundary means the established 15-second planner is
  // still the most efficient and fully backward-compatible choice.
  const ordered_boundaries = [...boundaries].sort((a, b) => a - b);
  if (!clipped_shots.length || ordered_boundaries.length <= 2) {
    return plan_render_segments(start, end, {
      max_segment_seconds: maximum,
      overlap_seconds: overlap,
      grid_seconds,
    });
  }

  const atoms: [number, number][] = [];
  for (let i = 0; i < ordered_boundaries.length - 1; i++) {
    const atomStart = ordered_boundaries[i]!;
    const atomEnd = ordered_boundaries[i + 1]!;
    let cursor = atomStart;
    while (atomEnd - cursor > maximum + 1e-6) {
      const split = snap_seconds(cursor + maximum, grid_seconds);
      atoms.push([cursor, split]);
      cursor = split;
    }
    if (atomEnd > cursor + 1e-6) atoms.push([cursor, atomEnd]);
  }

  const cores: [number, number][] = [];
  let index = 0;
  while (index < atoms.length) {
    const [atomStart] = atoms[index]!;
    let atomEnd = atoms[index]![1]!;
    while (
      atomEnd - atomStart < minimum - 1e-6 &&
      index + 1 < atoms.length &&
      atoms[index + 1]![1]! - atomStart <= maximum + 1e-6
    ) {
      index += 1;
      atomEnd = atoms[index]![1]!;
    }
    if (
      atomEnd - atomStart < minimum - 1e-6 &&
      cores.length &&
      atomEnd - cores[cores.length - 1]![0]! <= maximum + 1e-6
    ) {
      cores[cores.length - 1]![1] = atomEnd;
    } else {
      cores.push([atomStart, atomEnd]);
    }
    index += 1;
  }

  const result: RenderSegment[] = [];
  for (let coreIndex = 0; coreIndex < cores.length; coreIndex++) {
    const [core_start, core_end] = cores[coreIndex]!;
    // Continuity references describe the state immediately before this core —
    // never include the prior Shot as a leading generation handle.
    const render_start = core_start;
    const boundary_shot = clipped_shots.find(
      (row) => Math.abs(Number(row["start_seconds"]) - core_start) <= 1e-6,
    );
    const requested_mode = String(
      boundary_shot ? (boundary_shot["continuity_mode"] ?? "auto") : "auto",
    );
    let continuity_mode = requested_mode
      .trim()
      .toLowerCase()
      .replaceAll(" ", "_")
      .replaceAll("-", "_");
    if (!CONTINUITY_MODES.has(continuity_mode)) continuity_mode = "match_action";
    if (continuity_mode === "auto") continuity_mode = "match_action";
    if (coreIndex === 0) continuity_mode = "none";
    const shot_ids = clipped_shots
      .filter(
        (row) =>
          row["cue_id"] &&
          ranges_intersect(
            Number(row["start_seconds"]),
            Number(row["end_seconds"]),
            core_start,
            core_end,
          ),
      )
      .map((row) => String(row["cue_id"]));
    if (clipped_shots.length && !shot_ids.length) {
      throw new Error(
        `Shot-less render Segment ${fixed2(core_start)}-${fixed2(core_end)}s. ` +
          "Repair the Director Shot lane so it covers the complete Timeline.",
      );
    }
    result.push(
      new RenderSegment(shotSegmentId(core_start, core_end), coreIndex, render_start, core_end, {
        overlap_before_seconds: pyRound(core_start - render_start, 6),
        core_start_seconds: core_start,
        core_end_seconds: core_end,
        shot_ids,
        continuity_mode,
      }),
    );
  }
  for (let i = 0; i < result.length - 1; i++) {
    result[i]!.overlap_after_seconds = result[i + 1]!.overlap_before_seconds;
  }
  return result;
}

// ---- speech / atomic boundary protection ------------------------------------

type SpeechSpan = [number, number];

function speechSpans(
  speech_rows: PyRow[],
  grid_seconds: number,
  extra: (item: PyRow) => unknown[] = () => [],
): unknown[][] {
  return speech_rows
    .filter((item) =>
      SPEECH_CONTENT_ROLES.has(
        String(item["content_role"] ?? item["role"] ?? ""),
      ),
    )
    .map(
      (item): unknown[] =>
        [
          snap_seconds(pyFloat(item["start_seconds"], 0.0), grid_seconds),
          snap_seconds(
            pyFloat(item["end_seconds"], pyFloat(item["start_seconds"], 0.0)),
            grid_seconds,
          ),
          ...extra(item),
        ] as unknown[],
    );
}

const coreStart = (row: RenderSegment): number => {
  // Python: `if x is not None` semantics — 0.0 stays.
  return row.core_start_seconds !== null ? row.core_start_seconds : row.start_seconds;
};

function coreStartOrFalsy(row: RenderSegment): number {
  // Python: `x or y` semantics — 0.0 falls through (align pass quirk).
  return row.core_start_seconds || row.start_seconds;
}

function coreEnd(row: RenderSegment): number {
  return row.core_end_seconds !== null ? row.core_end_seconds : row.end_seconds;
}

export function protect_segment_boundaries_from_speech(
  segments: RenderSegment[],
  speech_rows: PyRow[],
  opts: {
    max_segment_seconds?: number;
    tail_seconds?: number;
    grid_seconds?: number;
  } = {},
): RenderSegment[] {
  const {
    max_segment_seconds = MAX_NATIVE_SECONDS,
    tail_seconds = 1.0,
    grid_seconds = TIMELINE_GRID_SECONDS,
  } = opts;
  // Move internal render cuts away from authored speech and its decay tail.
  const rows = segments.map((row) => row.clone());
  if (rows.length < 2) return rows;
  const maximum = Math.max(grid_seconds, snap_seconds(max_segment_seconds, grid_seconds));
  const tail = Math.max(0.0, snap_seconds(tail_seconds, grid_seconds));
  const speech = speechSpans(speech_rows, grid_seconds) as SpeechSpan[];
  speech.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  const live: SpeechSpan[] = speech.filter(([start, end]) => end > start + 1e-6);
  if (!live.length) return rows;

  // Overlapping authored clips form one indivisible speech event; adjacent
  // sequential lines stay separate so a safe cut can still be made between.
  const speech_groups: SpeechSpan[] = [];
  for (const [start, end] of live) {
    const last = speech_groups[speech_groups.length - 1];
    if (last && start < last[1] - 1e-6) {
      last[1] = Math.max(last[1], end);
    } else {
      speech_groups.push([start, end]);
    }
  }

  const boundaries: number[] = [coreStart(rows[0]!)];
  for (const row of rows) boundaries.push(coreEnd(row));
  const moved = new Set<number>();
  for (let index = 1; index < boundaries.length - 1; index++) {
    const boundary = boundaries[index]!;
    const hard_blockers = speech_groups.filter(
      ([start, end]) => start < boundary - 1e-6 && boundary < end - 1e-6,
    );
    const tail_blockers = speech_groups.filter(
      ([start, end]) =>
        start < boundary - 1e-6 && end - 1e-6 <= boundary && boundary < end + tail - 1e-6,
    );
    // A decay-tail preference must never move an already speech-safe cut
    // across the beginning of the next authored line.
    if (!hard_blockers.length && tail_blockers.length) {
      const preferred = snap_seconds(
        Math.max(...tail_blockers.map(([, end]) => end + tail)),
        grid_seconds,
      );
      if (
        speech_groups.some(
          ([start, end]) =>
            start >= boundary - 1e-6 && start < preferred - 1e-6 && end > boundary + 1e-6,
        )
      ) {
        continue;
      }
    }
    const blockers = hard_blockers.length ? hard_blockers : tail_blockers;
    if (!blockers.length) continue;
    const lower = Math.max(
      boundaries[index - 1]! + grid_seconds,
      boundaries[index + 1]! - maximum,
    );
    const upper = Math.min(
      boundaries[index + 1]! - grid_seconds,
      boundaries[index - 1]! + maximum,
    );
    const forward = snap_seconds(
      Math.max(...blockers.map(([, end]) => end + tail)),
      grid_seconds,
    );
    const backward = snap_seconds(Math.min(...blockers.map(([start]) => start)), grid_seconds);
    const forward_crosses_new_speech = speech_groups.some(
      ([start, end]) =>
        start >= boundary - 1e-6 &&
        start < forward - 1e-6 &&
        !blockers.some(([bs, be]) => bs === start && be === end),
    );
    let candidate: number | null = null;
    if (!forward_crosses_new_speech && lower - 1e-6 <= forward && forward <= upper + 1e-6) {
      candidate = forward;
    } else if (lower - 1e-6 <= backward && backward <= upper + 1e-6) {
      candidate = backward;
    } else if (
      boundaries[index - 1]! + grid_seconds - 1e-6 <= backward &&
      backward <= boundaries[index - 1]! + maximum + 1e-6 &&
      backward < boundaries[index + 1]! - 1e-6
    ) {
      // Moving backward keeps the current native request valid but may make
      // the following interval longer than 15 seconds — the rebuild pass
      // inserts a new safe boundary into that span.
      candidate = backward;
    }
    if (candidate === null || Math.abs(candidate - boundary) <= 1e-6) continue;
    boundaries[index] = candidate;
    moved.add(index);
  }

  // A completely packed sequence cannot always move one boundary without
  // making its neighbour exceed the native limit — insert extra native
  // windows instead of splitting one authored utterance.
  const safe_boundaries: number[] = [boundaries[0]!];
  for (const target of boundaries.slice(1)) {
    let cursor = safe_boundaries[safe_boundaries.length - 1]!;
    while (target - cursor > maximum + 1e-6) {
      let candidate = snap_seconds(cursor + maximum, grid_seconds);
      const blockers = speech_groups.filter(
        ([start, end]) => start < candidate - 1e-6 && candidate < end + tail - 1e-6,
      );
      if (blockers.length) {
        const backward = snap_seconds(Math.min(...blockers.map(([s]) => s)), grid_seconds);
        const forward = snap_seconds(Math.max(...blockers.map(([, e]) => e + tail)), grid_seconds);
        if (backward > cursor + 1e-6) {
          candidate = backward;
        } else if (forward <= cursor + maximum + 1e-6) {
          candidate = forward;
        } else {
          // One authored line itself exceeds a native H3 window — the Text
          // Layer still compiles into every intersecting window.
          candidate = snap_seconds(cursor + maximum, grid_seconds);
        }
      }
      if (candidate <= cursor + 1e-6) candidate = snap_seconds(cursor + maximum, grid_seconds);
      safe_boundaries.push(candidate);
      cursor = candidate;
    }
    if (target > safe_boundaries[safe_boundaries.length - 1]! + 1e-6) {
      safe_boundaries.push(target);
    }
  }
  const final_boundaries = safe_boundaries;

  const source_rows = rows;
  const rebuilt: RenderSegment[] = [];
  const original_starts = new Map<number, RenderSegment>();
  for (const row of source_rows) {
    original_starts.set(snap_seconds(coreStart(row), grid_seconds), row);
  }
  for (let index = 0; index < final_boundaries.length - 1; index++) {
    const core_start = snap_seconds(final_boundaries[index]!, grid_seconds);
    const core_end = snap_seconds(final_boundaries[index + 1]!, grid_seconds);
    let template = original_starts.get(core_start);
    if (template === undefined) {
      template =
        source_rows.find((row) =>
          ranges_intersect(coreStart(row), coreEnd(row), core_start, core_end),
        ) ?? source_rows[source_rows.length - 1]!;
    }
    const row = template.clone();
    row.index = index;
    row.start_seconds = core_start;
    row.end_seconds = core_end;
    row.core_start_seconds = core_start;
    row.core_end_seconds = core_end;
    row.overlap_before_seconds = 0.0;
    row.overlap_after_seconds = 0.0;
    row.segment_id = shotSegmentId(core_start, core_end);
    if (index && (moved.has(index) || !original_starts.has(core_start))) {
      row.continuity_mode = "motion_reference";
    } else if (index === 0) {
      row.continuity_mode = "none";
    }
    rebuilt.push(row);
  }
  return rebuilt;
}

export function protect_segment_boundaries_from_atomic_shots(
  segments: RenderSegment[],
  shots: PyRow[],
  opts: {
    text_layers?: PyRow[];
    max_segment_seconds?: number;
    grid_seconds?: number;
  } = {},
): RenderSegment[] {
  const {
    text_layers = [],
    max_segment_seconds = MAX_NATIVE_SECONDS,
    grid_seconds = TIMELINE_GRID_SECONDS,
  } = opts;
  // Keep one named/atomic technique inside one native H3 request.
  const authored_layers = text_layers.filter(
    (row): row is PyRow =>
      isRow(row) &&
      ATOMIC_SHOT_RE.test(String(pyOr(pyOr(row["content"], row["text"]), ""))),
  );
  const maximum = Math.max(grid_seconds, snap_seconds(max_segment_seconds, grid_seconds));
  const atomic_rows: PyRow[] = [];
  for (const shot of shots) {
    const start = snap_seconds(pyFloat(shot["start_seconds"], 0.0), grid_seconds);
    const end = snap_seconds(pyFloat(shot["end_seconds"], start), grid_seconds);
    const action_text = [
      "subject_action", "h3_executable_action", "combat_action_chain",
      "additional_direction", "preset",
    ]
      .map((key) => String(shot[key] ?? ""))
      .join(" ");
    let is_atomic =
      pyTruth(shot["atomic_render"]) || ATOMIC_SHOT_RE.test(action_text);
    if (!is_atomic) {
      const shot_id = (pyTruth(pyOr(shot["id"], shot["cue_id"]))
        ? String(pyOr(shot["id"], shot["cue_id"]))
        : "").trim();
      is_atomic = authored_layers.some(
        (layer) =>
          (shot_id && String(layer["shot_id"] ?? "").trim() === shot_id) ||
          (pyFloat(layer["start_seconds"], 0.0) < end - 1e-6 &&
            pyFloat(layer["end_seconds"], 0.0) > start + 1e-6),
      );
    }
    if (is_atomic && end > start + 1e-6 && end - start <= maximum + 1e-6) {
      atomic_rows.push({
        content_role: "dialogue",
        start_seconds: start,
        end_seconds: end,
      });
    }
  }
  if (!atomic_rows.length) return segments.map((row) => row.clone());
  return protect_segment_boundaries_from_speech(segments, atomic_rows, {
    max_segment_seconds: maximum,
    tail_seconds: 0.0,
    grid_seconds,
  });
}

// ---- dialogue-turn alignment -------------------------------------------------

type SpeechTurn = [number, number, string, string, boolean];

export function align_segments_to_dialogue_turns(
  segments: RenderSegment[],
  speech_rows: PyRow[],
  opts: { max_segment_seconds?: number; grid_seconds?: number } = {},
): RenderSegment[] {
  const { max_segment_seconds = MAX_NATIVE_SECONDS, grid_seconds = TIMELINE_GRID_SECONDS } = opts;
  // Give alternating on-camera speakers separate request boundaries.
  const rows = segments.map((row) => row.clone());
  if (!rows.length) return rows;
  const speech = speechSpans(speech_rows, grid_seconds, (item) => [
    String(item["content_role"] ?? item["role"] ?? ""),
    String(item["speaker"] ?? "S1"),
    pyTruth(
      "lip_sync" in item ? item["lip_sync"]
      : "requires_lip_sync" in item ? item["requires_lip_sync"]
      : true,
    ),
  ]) as SpeechTurn[];
  speech.sort(
    (a, b) =>
      a[0] - b[0] ||
      a[1] - b[1] ||
      (a[2] < b[2] ? -1 : a[2] > b[2] ? 1 : 0) ||
      (a[3] < b[3] ? -1 : a[3] > b[3] ? 1 : 0) ||
      (a[4] === b[4] ? 0 : a[4] ? 1 : -1),
  );
  // Speaker-boundary splitting is only needed for a visibly lip-synced
  // on-camera turn; non-lip-synced exertion shouts must not cut one combat
  // causal chain into two independent requests.
  const dialogue = speech.filter((row) => row[2] === "dialogue" && row[1] > row[0] && row[4]);
  if (!dialogue.length) return rows;

  const boundaries: number[] = [coreStartOrFalsy(rows[0]!)];
  for (const row of rows) boundaries.push(coreEnd(row));
  const maximum = Math.max(grid_seconds, snap_seconds(max_segment_seconds, grid_seconds));

  // Move an internal boundary forward through genuine silence so the first
  // on-camera line starts at local 0.00s — never exceed the native duration.
  for (let index = 1; index < boundaries.length - 1; index++) {
    const start = boundaries[index]!;
    const end = boundaries[index + 1]!;
    const turns = dialogue.filter((row) => start < row[0] && row[0] < end - 1e-6);
    if (!turns.length) continue;
    const first = turns[0]![0];
    const has_prior_speech = speech.some(
      ([speech_start, speech_end]) =>
        speech_start < first - 1e-6 && speech_end > start + 1e-6,
    );
    if (!has_prior_speech && first - boundaries[index - 1]! <= maximum + 1e-6) {
      boundaries[index] = first;
    }
  }

  // A later change of speaking face receives its own request; same-speaker
  // continuation stays together unless a long authored silence separates it.
  const inserts = new Set<number>();
  for (let i = 0; i < boundaries.length - 1; i++) {
    const start = boundaries[i]!;
    const end = boundaries[i + 1]!;
    const turns = dialogue.filter((row) => start - 1e-6 <= row[0] && row[0] < end - 1e-6);
    for (let t = 0; t < turns.length - 1; t++) {
      const previous = turns[t]!;
      const current = turns[t + 1]!;
      // Simultaneous or interrupting dialogue belongs to one request — a cut
      // at the later speaker's start would truncate the earlier Text Layer.
      if (current[0] < previous[1] - 1e-6) continue;
      const silent_gap = current[0] - previous[1];
      if (current[3] !== previous[3] || silent_gap >= 1.5 - 1e-6) {
        const boundary_cuts_speech = speech.some(
          ([speech_start, speech_end]) =>
            speech_start < current[0] - 1e-6 && current[0] < speech_end - 1e-6,
        );
        if (!boundary_cuts_speech && current[0] - start >= grid_seconds - 1e-6) {
          inserts.add(current[0]);
        }
      }
    }
  }
  const final_boundaries = [...new Set([...boundaries, ...inserts])].sort((a, b) => a - b);

  const rebuilt: RenderSegment[] = [];
  const original_starts = new Map<number, RenderSegment>();
  for (const row of rows) {
    original_starts.set(snap_seconds(coreStart(row), grid_seconds), row);
  }
  for (let index = 0; index < final_boundaries.length - 1; index++) {
    const core_start = final_boundaries[index]!;
    const core_end = final_boundaries[index + 1]!;
    const template =
      rows.find((row) => ranges_intersect(coreStart(row), coreEnd(row), core_start, core_end)) ??
      rows[rows.length - 1]!;
    const row = template.clone();
    row.index = index;
    row.start_seconds = row.core_start_seconds = core_start;
    row.end_seconds = row.core_end_seconds = core_end;
    row.overlap_before_seconds = row.overlap_after_seconds = 0.0;
    row.segment_id = shotSegmentId(core_start, core_end);
    if (index === 0) row.continuity_mode = "none";
    else if (original_starts.has(core_start)) {
      row.continuity_mode = original_starts.get(core_start)!.continuity_mode;
    } else row.continuity_mode = "motion_reference";
    rebuilt.push(row);
  }
  return rebuilt;
}

// ---- speech lanes ------------------------------------------------------------

export function normalize_speech_overlap_policy(value: unknown): string {
  const normalized = (pyTruth(value) ? String(value) : "auto")
    .trim()
    .toLowerCase()
    .replaceAll("-", "_")
    .replaceAll(" ", "_");
  const aliases: Record<string, string> = {
    allow: "overlap",
    allow_overlap: "overlap",
    intentional: "overlap",
    intentional_overlap: "overlap",
    no_overlap: "sequential",
    sequence: "sequential",
  };
  const resolved = aliases[normalized] ?? normalized;
  return SPEECH_OVERLAP_POLICIES.has(resolved) ? resolved : "auto";
}

export function plan_speech_track_lanes(
  speech_rows: PyRow[],
  opts: { grid_seconds?: number; guard_seconds?: number } = {},
): PyRow[] {
  const { grid_seconds = TIMELINE_GRID_SECONDS, guard_seconds = 1.0 } = opts;
  // Assign independent speech clips to the lowest collision-free role lane.
  const prepared: PyRow[] = [];
  speech_rows.forEach((item, index) => {
    const role = String(item["content_role"] ?? item["role"] ?? "").trim();
    if (!SPEECH_CONTENT_ROLES.has(role)) return;
    // AUTO/OVERLAP must never quantize the user's authored timing.
    const start = Math.max(0.0, pyFloat(item["start_seconds"], 0.0));
    let end = pyFloat(item["end_seconds"], pyFloat(item["start_seconds"], 0.0));
    if (end <= start + 1e-6) end = start + grid_seconds;
    prepared.push({
      source_index: index,
      layer_id: String(item["layer_id"] ?? item["id"] ?? `speech-${index + 1}`),
      content_role: role,
      start_seconds: start,
      end_seconds: end,
      overlap_policy: normalize_speech_overlap_policy(item["overlap_policy"] ?? "auto"),
    });
  });

  prepared.sort(
    (a, b) =>
      (a["start_seconds"] as number) - (b["start_seconds"] as number) ||
      (a["end_seconds"] as number) - (b["end_seconds"] as number) ||
      (String(a["layer_id"]) < String(b["layer_id"]) ? -1 : String(a["layer_id"]) > String(b["layer_id"]) ? 1 : 0) ||
      (a["source_index"] as number) - (b["source_index"] as number),
  );
  const guard = Math.max(0.0, snap_seconds(guard_seconds, grid_seconds));
  const lane_ends = new Map<string, number[]>();
  const role_latest_end = new Map<string, number>();
  for (const role of SPEECH_CONTENT_ROLES) {
    lane_ends.set(role, []);
    role_latest_end.set(role, 0.0);
  }
  const result: PyRow[] = [];
  for (const row of prepared) {
    const role = String(row["content_role"]);
    let start = Number(row["start_seconds"]);
    let end = Number(row["end_seconds"]);
    const duration = end - start;
    let adjusted = false;
    if (row["overlap_policy"] === "sequential" && start < role_latest_end.get(role)! - 1e-6) {
      start = snap_seconds(role_latest_end.get(role)!, grid_seconds);
      end = snap_seconds(start + duration, grid_seconds);
      adjusted = true;
    }

    const lanes = lane_ends.get(role)!;
    let lane_index = lanes.findIndex(
      (occupied_until) =>
        occupied_until - (row["overlap_policy"] === "sequential" ? guard : 0.0) <= start + 1e-6,
    );
    if (lane_index === -1) lane_index = lanes.length;
    if (lane_index === lanes.length) lanes.push(end + guard);
    else lanes[lane_index] = end + guard;
    role_latest_end.set(role, Math.max(role_latest_end.get(role)!, end));
    result.push({
      ...row,
      start_seconds: start,
      end_seconds: end,
      lane_number: lane_index + 1,
      timing_adjusted: adjusted,
    });
  }
  return result.sort(
    (a, b) => (a["source_index"] as number) - (b["source_index"] as number),
  );
}

// ---- seeds / ranges / cache ---------------------------------------------------

export function derive_segment_seed(master_seed: number, segment_index: number): bigint {
  const digest = sha256Hex(`h3-smart-render:${Math.trunc(master_seed)}:${segment_index}`);
  return BigInt("0x" + digest.slice(0, 16)) % MAX_SEED;
}

export function derive_named_segment_seed(master_seed: number, segment_id: string): bigint {
  const digest = sha256Hex(`h3-smart-render:${Math.trunc(master_seed)}:${segment_id}`);
  return BigInt("0x" + digest.slice(0, 16)) % MAX_SEED;
}

export function ranges_intersect(
  start_a: number,
  end_a: number,
  start_b: number,
  end_b: number,
): boolean {
  // True for intervals and zero-duration markers inside a range.
  if (Math.abs(end_a - start_a) <= 1e-9) return start_b <= start_a && start_a < end_b;
  return start_a < end_b && end_a > start_b;
}

export function dirty_segment_indexes(
  segments: RenderSegment[],
  change_start: number,
  change_end: number,
): number[] {
  // Find only the hidden jobs touched by a timeline edit.
  let start = change_start;
  let end = change_end;
  if (end < start) [start, end] = [end, start];
  if (Math.abs(end - start) <= 1e-9) end = start;
  return segments
    .filter((segment) =>
      ranges_intersect(start, end, segment.start_seconds, segment.end_seconds),
    )
    .map((segment) => segment.index);
}

export function rebase_timed_rows(
  rows: PyRow[],
  window_start: number,
  window_end: number,
  opts: { clamp?: boolean } = {},
): PyRow[] {
  const { clamp = true } = opts;
  // Filter timeline dictionaries to a segment and convert to local time.
  const result: PyRow[] = [];
  for (const source of rows) {
    let row_start = pyFloat(source["start_seconds"], 0.0);
    let row_end = pyFloat(source["end_seconds"], row_start);
    if (!ranges_intersect(row_start, row_end, window_start, window_end)) continue;
    const local = { ...source };
    if (clamp) {
      row_start = Math.max(window_start, row_start);
      row_end = Math.min(window_end, row_end);
    }
    local["start_seconds"] = pyRound(Math.max(0.0, row_start - window_start), 6);
    local["end_seconds"] = pyRound(Math.max(0.0, row_end - window_start), 6);
    result.push(local);
  }
  return result;
}

export function content_fingerprint(value: unknown): string {
  // Stable hash for workflow, prompt, assets, and render parameters.
  return createHash("sha256").update(pyStableDumps(value), "utf8").digest("hex");
}

export function reuse_cached_segments(
  planned: RenderSegment[],
  cached: PyRow[],
): RenderSegment[] {
  // Copy completed outputs only when a segment fingerprint still matches.
  const cache_by_id = new Map<string, PyRow>();
  for (const row of cached) cache_by_id.set(String(row["segment_id"] ?? ""), row);
  const result: RenderSegment[] = [];
  for (const segment of planned) {
    const old = cache_by_id.get(segment.segment_id);
    if (old && old["fingerprint"] === segment.fingerprint && pyTruth(old["output_path"])) {
      segment.output_path = String(old["output_path"]);
      segment.status = "cached";
    }
    result.push(segment);
  }
  return result;
}

// ---- SEG1 ②: PREVIEW 0.2M low-cost preview flag (TS-side layer) --------------
//
// The Python engine has no preview concept (only the seed-stability hook for
// "preview acceptance"); the 0.2M preview lane is authored here as a pure
// data flag. Preview ONLY downgrades graph steps and resolution; the formal
// path values (config.ts 864x480/steps 8) are never read or mutated here.

export type SegmentRenderProfile = { steps: number; width: number; height: number };

/** ≈0.204MP (608x336) at 4 steps, same 44:25 aspect as the 864x480 native. */
export const SEGMENT_PREVIEW_PROFILE: SegmentRenderProfile = {
  steps: 4,
  width: 608,
  height: 336,
};

/**
 * Flag gate: disabled → the production profile passes through untouched
 * (byte-equal values); enabled → the preview profile replaces steps AND
 * resolution. Pure function, never mutates the input.
 */
export function apply_segment_render_profile(
  enabled: boolean,
  production: SegmentRenderProfile,
): SegmentRenderProfile {
  return enabled ? { ...SEGMENT_PREVIEW_PROFILE } : { ...production };
}

// ---- SEG1 ④: long-episode dialogue segmentation entry -------------------------
//
// Composition order (TS glue; the h3studio app calls these passes from UI
// code, not from the module): shot-aligned planning → atomic-shot protection
// (named techniques stay whole) → speech+tail protection (utterances stay
// whole) → dialogue-turn alignment LAST (it moves safe cuts onto turn starts
// and inserts speaker-change boundaries; running it earlier would let the
// speech pass drag those cuts away again). Pipeline wiring waits for Chau.

export type LongFormDialoguePlanOpts = {
  shots?: PyRow[];
  speech_rows?: PyRow[];
  text_layers?: PyRow[];
  min_segment_seconds?: number;
  max_segment_seconds?: number;
  overlap_seconds?: number;
  tail_seconds?: number;
  grid_seconds?: number;
};

export function plan_long_form_dialogue_segments(
  start_seconds: number,
  end_seconds: number,
  opts: LongFormDialoguePlanOpts = {},
): RenderSegment[] {
  const {
    shots = [],
    speech_rows = [],
    text_layers = [],
    min_segment_seconds,
    max_segment_seconds,
    overlap_seconds,
    tail_seconds,
    grid_seconds = TIMELINE_GRID_SECONDS,
  } = opts;
  let rows = plan_shot_render_segments(start_seconds, end_seconds, shots, {
    ...(min_segment_seconds !== undefined ? { min_segment_seconds } : {}),
    ...(max_segment_seconds !== undefined ? { max_segment_seconds } : {}),
    ...(overlap_seconds !== undefined ? { overlap_seconds } : {}),
    grid_seconds,
  });
  rows = protect_segment_boundaries_from_atomic_shots(rows, shots, {
    text_layers,
    ...(max_segment_seconds !== undefined ? { max_segment_seconds } : {}),
    grid_seconds,
  });
  rows = protect_segment_boundaries_from_speech(rows, speech_rows, {
    ...(max_segment_seconds !== undefined ? { max_segment_seconds } : {}),
    ...(tail_seconds !== undefined ? { tail_seconds } : {}),
    grid_seconds,
  });
  return align_segments_to_dialogue_turns(rows, speech_rows, {
    ...(max_segment_seconds !== undefined ? { max_segment_seconds } : {}),
    grid_seconds,
  });
}
