import type { MaterialPreset, MaterialState } from "./types";

const PRESETS: Record<
  MaterialPreset,
  Omit<MaterialState, "preset" | "color"> & { color: string }
> = {
  plastic: {
    color: "#6b7c93",
    roughness: 0.42,
    metalness: 0,
    transmission: 0,
    ior: 1.45,
    emission: "#000000",
    emissionStrength: 0,
  },
  matte: {
    color: "#8a9099",
    roughness: 0.86,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  glossy: {
    color: "#d0d6e0",
    roughness: 0.12,
    metalness: 0.05,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  rubber: {
    color: "#2a2a2c",
    roughness: 0.78,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  clay: {
    color: "#c4b7a5",
    roughness: 0.92,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  metal: {
    color: "#8d949e",
    roughness: 0.28,
    metalness: 1,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  chrome: {
    color: "#cfd5dd",
    roughness: 0.04,
    metalness: 1,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  gold: {
    color: "#d4af37",
    roughness: 0.22,
    metalness: 1,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  copper: {
    color: "#b87333",
    roughness: 0.3,
    metalness: 1,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  silver: {
    color: "#c0c7d1",
    roughness: 0.12,
    metalness: 1,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  glass: {
    color: "#d7f3ff",
    roughness: 0.04,
    metalness: 0,
    transmission: 1,
    ior: 1.45,
    emission: "#000000",
    emissionStrength: 0,
  },
  toon: {
    color: "#5b8def",
    roughness: 1,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  marble: {
    color: "#ece7df",
    roughness: 0.34,
    metalness: 0.08,
    transmission: 0,
    ior: 1.5,
    emission: "#000000",
    emissionStrength: 0,
  },
  wood: {
    color: "#8a5a32",
    roughness: 0.7,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  emissive: {
    color: "#111111",
    roughness: 0.4,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#7ecbff",
    emissionStrength: 4.5,
  },
  foliage: {
    color: "#3f8f4a",
    roughness: 0.82,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  skin: {
    color: "#e8c4a8",
    roughness: 0.62,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  asphalt: {
    color: "#3a3d44",
    roughness: 0.88,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#000000",
    emissionStrength: 0,
  },
  water: {
    color: "#1d4f78",
    roughness: 0.08,
    metalness: 0.15,
    transmission: 0.35,
    ior: 1.33,
    emission: "#000000",
    emissionStrength: 0,
  },
  sky: {
    color: "#7eb6e8",
    roughness: 1,
    metalness: 0,
    transmission: 0,
    ior: 1.4,
    emission: "#9ec9f0",
    emissionStrength: 1.4,
  },
};

export const MATERIAL_WORDS: Record<string, MaterialPreset> = {
  plastic: "plastic",
  matte: "matte",
  clay: "clay",
  glossy: "glossy",
  shiny: "glossy",
  rubber: "rubber",
  metal: "metal",
  metallic: "metal",
  steel: "metal",
  iron: "metal",
  chrome: "chrome",
  mirror: "chrome",
  gold: "gold",
  golden: "gold",
  copper: "copper",
  bronze: "copper",
  silver: "silver",
  glass: "glass",
  crystal: "glass",
  transparent: "glass",
  toon: "toon",
  cartoon: "toon",
  marble: "marble",
  stone: "marble",
  wood: "wood",
  wooden: "wood",
  neon: "emissive",
  emissive: "emissive",
  glowing: "emissive",
  glow: "emissive",
  foliage: "foliage",
  grass: "foliage",
  skin: "skin",
  asphalt: "asphalt",
  road: "asphalt",
  water: "water",
  ocean: "water",
  sky: "sky",
};

export const COLOR_WORDS: Record<string, string> = {
  red: "#e23d3d",
  crimson: "#9b1b30",
  scarlet: "#ff2e2e",
  orange: "#e87d0d",
  amber: "#f5a524",
  yellow: "#f0d14a",
  gold: "#d4af37",
  lime: "#84cc16",
  green: "#3dba6e",
  emerald: "#10b981",
  teal: "#2ec4b6",
  cyan: "#3ec6e0",
  blue: "#3b82f6",
  navy: "#1e3a5f",
  indigo: "#6366f1",
  purple: "#8b5cf6",
  violet: "#7c3aed",
  magenta: "#d946ef",
  pink: "#f472b6",
  white: "#f4f4f5",
  ivory: "#fffff0",
  black: "#1a1a1a",
  gray: "#8a8f98",
  grey: "#8a8f98",
  charcoal: "#364054",
  brown: "#7a4e2d",
  beige: "#d7c4a5",
  cream: "#f3ead8",
};

export function materialFromPreset(
  preset: MaterialPreset,
  color?: string,
): MaterialState {
  const base = PRESETS[preset];
  return {
    preset,
    ...base,
    color: color ?? base.color,
    emission: preset === "emissive" ? (color ?? base.emission) : base.emission,
  };
}

export const ALL_PRESETS = Object.keys(PRESETS) as MaterialPreset[];
